<?php $this->headtitle("Resources");

?>

<div class="row">
    <!--  <div class="col-lg-4 col-sm-12">
        <div class="card mt-4">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-4">
                        <img src="../../assets/img/kal-visuals-square.jpg" alt="kal" class="border-radius-lg shadow w-100">
                    </div>
                    <div class="col-8 my-auto">
                        <p class="text-muted text-sm font-weight-bold">
                            Today is Martina's birthday. Wish her the best of luck!
                        </p>
                        <a href="javascript:;" class="btn btn-sm bg-gradient-dark mb-0">Send message</a>
                    </div>
                </div>
            </div>
        </div>

    </div> -->

    <div class="col-lg-4 col-sm-12">
        <div class="card mt-4">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-4">

                        <i class="fa fa-file border-radius-lg shadow w-50"></i>
                    </div>
                    <div class="col-8 my-auto">
                        <p class="text-muted text-sm font-weight-bold">
                            Access Training Documents
                        </p>
                        <a href="<?= $this->url("internship", ["controller" => "resources", "action" => "documents"]) ?>" class="btn btn-sm bg-gradient-dark mb-0">View</a>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-4 col-sm-12">
        <div class="card mt-4">
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-4">

                        <i class="fa fa-video border-radius-lg shadow w-50"></i>
                    </div>
                    <div class="col-8 my-auto">
                        <p class="text-muted text-sm font-weight-bold">
                            Access all zoom pre-recoreded videos
                        </p>
                        <a href="<?= $this->url("internship", ["controller" => "resources", "action" => "video"]) ?>" class="btn btn-sm bg-gradient-dark mb-0">View</a>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>