<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Courses extends \Application\Entity\Courses implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'uuid', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'programs', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'title', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'updatedOn', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'banner', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'video', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'courseContent', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'isQuiz', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'quiz'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'uuid', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'programs', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'title', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'updatedOn', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'banner', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'video', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'courseContent', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'isQuiz', '' . "\0" . 'Application\\Entity\\Courses' . "\0" . 'quiz'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Courses $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid(string $uuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograms', []);

        return parent::getPrograms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrograms(\Application\Entity\Programs $programs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrograms', [$programs]);

        return parent::setPrograms($programs);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\Datetime $createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\Datetime $updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanner', []);

        return parent::getBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanner(\General\Entity\Image $banner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanner', [$banner]);

        return parent::setBanner($banner);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(\General\Entity\Image $video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseContent', []);

        return parent::getCourseContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseContent(\Doctrine\Common\Collections\Collection $courseContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseContent', [$courseContent]);

        return parent::setCourseContent($courseContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsQuiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsQuiz', []);

        return parent::getIsQuiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsQuiz(bool $isQuiz)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsQuiz', [$isQuiz]);

        return parent::setIsQuiz($isQuiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuiz()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuiz', []);

        return parent::getQuiz();
    }

}
