<div class="row">
    <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
        <div class="card card-plain">
            <div class="card-body px-lg-5 py-lg-5 text-center">
                <div class="text-center text-muted mb-4">
                    <h2>Email Confirmation Successfull</h2>
                </div>
                <div class="row gx-2 gx-sm-3">
                    <p>Email Successfully confimrd please login to your account </p>
                </div>
                <div class="text-center">

                    <span class="text-muted text-sm">Haven't received it?<a href="<?= $this->url("login") ?>"> Login</a>.</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
        <div class="position-relative bg-gradient-warning h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="../../../assets/img/shapes/pattern-lines.svg" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2" src="../../../assets/img/illustrations/danger-chat-ill.png" alt="chart-ill">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
        </div>
    </div>
</div>