<?= $this->headtitle("New Password"); ?>


<section id="ress" class="register_section section_space_lg">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col col-lg-5">
                <h1 class="register_heading text-center">New Password</h1>
                <p class="register_heading_description text-center">
                    Provide us with your email
                </p>

                <div class="register_form signup_login_form">
                    <div class="form_item">
                        <input v-model="password" type="password" name="email" placeholder="Username or Email">
                    </div>
                    <div class="form_item">
                        <input v-model="passwordz" type="password" name="email" placeholder="Username or Email">
                    </div>
                    <div v-if="isSubmitting">
                        <i class="fas fa-spinner fs-3x"></i>
                    </div>
                    <div v-else>
                        <button @click="newpassword" type="submit" class="btn btn_dark mb-5">
                            <span>
                                <small>Send Password</small>
                                <small>Send Password</small>
                            </span>
                        </button>
                    </div>

                </div>


            </div>

        </div>
    </div>

</section>
<script>
    const app = Vue.createApp({
        data() {
            return {
                isSubmitting: false,
                password: '',
                passwordz: '',
                token: '<?= $token ?>',
            }
        },
        methods: {
            newpassword() {
                this.isSubmitting = true;
                if (this.password == "" || this.passwordz == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Empty field",
                        text: "Email Field is empty"
                    })
                } else {
                    let formData = new FormData();
                    formData.append("password", this.password);
                    formData.append("token", this.token);
                    formData.append("passwordz", this.passwordz);
                    axios.post("/auth/newpassword", formData).then((result) => {
                        if (result.status == 201) {
                            Swal.fire({
                                icon: "success",
                                title: "Password Success",
                                test: "Your password has successfully reset"
                            }).then(ress => {
                                if (ress.isConfirmed) {
                                    window.location.href = "/login";
                                }
                            });
                            this.isSubmitting = false;
                        }
                    }).catch((err) => {
                        Swal.fire({
                            icon: "error",
                            title: "Ooops...",
                            text: "An error occured",
                        });
                    });
                }

            }
        },
    });
    app.mount("#ress");
</script>