<?php echo $this->headtitle("Reset Password"); ?>


<section id="ress" class="register_section section_space_lg">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col col-lg-5">
                <h1 class="register_heading text-center">Reset Password</h1>
                <p class="register_heading_description text-center">
                    Provide us with your email
                </p>

                <div class="register_form signup_login_form">
                    <div class="form_item">
                        <input v-model="email" type="email" name="email" placeholder="Username or Email">
                    </div>
                    <div v-if="isSubmitting">
                        <i class="fas fa-spinner fs-3x"></i>
                    </div>
                    <div v-else>
                        <button @click="reset" type="submit" class="btn btn_dark mb-5">
                            <span>
                                <small>Reset</small>
                                <small>Reset</small>
                            </span>
                        </button>
                    </div>

                </div>


            </div>

        </div>
    </div>

</section>
<script>
    const app = Vue.createApp({
        data() {
            return {
                isSubmitting: false,
                email: ""
            }
        },
        methods: {
            reset() {
                this.isSubmitting = true;
                if (this.email == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Empty field",
                        text: "Email Field is empty"
                    })
                } else {
                    let formData = new FormData();
                    formData.append("email", this.email);
                    axios.post("/auth/reset", formData).then((result) => {
                        if (result.status == 201) {
                            Swal.fire({
                                icon: "success",
                                title: "Reset Link sent",
                                test: "A reset link has been sent to you email"
                            });
                            this.isSubmitting = false;
                        }
                    }).catch((err) => {

                    });
                }

            }
        },
    });
    app.mount("#ress");
</script>