<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        // ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('/assets/css/vanilla-calendar.min.css'))
        ->prependStylesheet($this->basePath('/assets/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('/assets/css/slick-theme.css'))
        ->prependStylesheet($this->basePath('/assets/css/slick.css'))
        ->prependStylesheet($this->basePath('/assets/css/cursor.css'))
        ->prependStylesheet($this->basePath('/assets/css/animate.css'))
        ->prependStylesheet($this->basePath('/assets/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('/assets/css/bootstrap.min.css'))
    ?>


    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <main class="page_content">
        <?php
        $flashMessenger = $this->flashMessenger()
            ->setMessageOpenFormat('<div%s  role="alert">
                <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
     <ul><li>')

            ->setMessageCloseString('</div>');
        ?>
        <?php echo $flashMessenger->render('error', ['alert', 'alert-dismissable', 'alert-danger']); ?>
        <?php echo $flashMessenger->render('info', ['alert', 'alert-dismissable', 'alert-info']); ?>
        <?php echo $flashMessenger->render('default', ['alert', 'alert-dismissable', 'alert-warning']); ?>
        <?php echo $flashMessenger->render('success', ['alert', 'alert-dismissable', 'alert-success']); ?>
        <?= $this->content ?>
    </main>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
    ?>
</body>

</html>