<?php echo $this->headtitle("Video"); 

?>


<div class="row">
    <div class="col-lg-12 col-12">
        <div class="card">
            <div class="table-responsive">
                <table class="table align-items-center mb-0">
                    <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Title</th>

                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Description</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Uploaded On</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data as $da) : ?>
                            <tr>
                                <td>
                                    <div class="d-flex px-2 py-1">

                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-sm"><?= $da["titles"] ?></h6>
                                        </div>
                                        <a href=""></a>
                                    </div>
                                </td>

                                <td class="align-middle text-center text-sm">
                                    <p class="text-secondary mb-0 text-sm"><?= substr($da["descs"], 0, 100) . "..." ?></p>
                                </td>
                                <td class="align-middle text-center">
                                    <span class="text-secondary text-sm"><?= $this->dateFormat($da["createdOn"], IntlDateFormatter::LONG, IntlDateFormatter::NONE) ?></span>
                                </td>
                                <td class="align-middle text-center">
                                    <span class="text-secondary text-sm"><a href="<?= $da["imageUrl"] ?>"><i class="fa fa-download"></i></a></span>
                                </td>
                            </tr>
                        <?php 
                        // var_dump($da["video"]);
                        endforeach ?>
                        <!--  <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div>
                                        <img src="../../../assets/img/team-3.jpg" class="avatar avatar-sm me-3" alt="avatar image">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Alexa Liras</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-sm text-secondary mb-0">Programator</p>
                            </td>
                            <td>
                                <span class="badge badge-dot me-4">
                                    <i class="bg-info"></i>
                                    <span class="text-dark text-xs">positive</span>
                                </span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <p class="text-secondary mb-0 text-sm">alexa@user.com</p>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-xs font-weight-bold">11/01/19</span>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-sm">93021</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div>
                                        <img src="../../../assets/img/team-4.jpg" class="avatar avatar-sm me-3" alt="avatar image">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Laurent Perrier</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-sm text-secondary mb-0">Executive</p>
                            </td>
                            <td>
                                <span class="badge badge-dot me-4">
                                    <i class="bg-dark"></i>
                                    <span class="text-dark text-xs">neutral</span>
                                </span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <p class="text-secondary mb-0 text-sm">laurent@user.com</p>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-xs font-weight-bold">19/09/17</span>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-sm">10392</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div>
                                        <img src="../../../assets/img/team-3.jpg" class="avatar avatar-sm me-3" alt="avatar image">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Michael Levi</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-sm text-secondary mb-0">Backend developer</p>
                            </td>
                            <td>
                                <span class="badge badge-dot me-4">
                                    <i class="bg-info"></i>
                                    <span class="text-dark text-xs">positive</span>
                                </span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <p class="text-secondary mb-0 text-sm">michael@user.com</p>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-xs font-weight-bold">24/12/08</span>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-sm">34002</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div>
                                        <img src="../../../assets/img/team-2.jpg" class="avatar avatar-sm me-3" alt="avatar image">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Richard Gran</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-sm text-secondary mb-0">Manager</p>
                            </td>
                            <td>
                                <span class="badge badge-dot me-4">
                                    <i class="bg-danger"></i>
                                    <span class="text-dark text-xs">negative</span>
                                </span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <p class="text-secondary mb-0 text-sm">richard@user.com</p>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-xs font-weight-bold">04/10/21</span>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-sm">91879</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex px-2 py-1">
                                    <div>
                                        <img src="../../../assets/img/team-4.jpg" class="avatar avatar-sm me-3" alt="avatar image">
                                    </div>
                                    <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Miriam Eric</h6>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <p class="text-sm text-secondary mb-0">Programtor</p>
                            </td>
                            <td>
                                <span class="badge badge-dot me-4">
                                    <i class="bg-info"></i>
                                    <span class="text-dark text-xs">positive</span>
                                </span>
                            </td>
                            <td class="align-middle text-center text-sm">
                                <p class="text-secondary mb-0 text-sm">miriam@user.com</p>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-xs font-weight-bold">14/09/20</span>
                            </td>
                            <td class="align-middle text-center">
                                <span class="text-secondary text-sm">23042</span>
                            </td>
                        </tr> -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>