<ul class="nav">
    <!-- <li class="nav-item ">
        <a class="nav-link" href="">
            <i class="icon ion-ios-home-outline"></i>
            <span>REGISTERED USERS</span>
        </a>

    </li>

    <li class="nav-item">
        <a class="nav-link" href="">
            <i class="icon ion-ios-filing-outline"></i>
            <span>CREATE COHORT</span>
        </a>

    </li>

    <li class="nav-item">
        <a class="nav-link" href="">
            <i class="icon ion-ios-filing-outline"></i>
            <span>CREATE CLASS CONTENT</span>
        </a>

    </li> -->

    <li class="nav-item with-sub">
        <a class="nav-link" href="#" data-toggle="dropdown">
            <i class="icon ion-ios-chatboxes-outline"></i>
            <span>Oracle P6</span>

        </a>
        <div class="sub-item">
            <ul>
                <li><a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "registered-users"]) ?>">REGISTERED USER</a></li>
                <li><a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "create-cohort"]) ?>">CREATE COHORT</a></li>
                <li><a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "create-content"]) ?>">PROCESS COHORT</a></li>

                <!-- <li><a href="form-rangeslider.html">Range Slider</a></li>
                <li><a href="form-datepicker.html">Datepicker</a></li> -->
            </ul>
        </div>
    </li>

    <li class="nav-item with-sub">
        <a class="nav-link" href="#" data-toggle="dropdown">
            <i class="icon ion-ios-chatboxes-outline"></i>
            <span>Free Master Class</span>

        </a>
        <div class="sub-item">
            <ul>
                <li><a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "free-master-class-cohort"]) ?>">CREATE COHORT</a></li>
                <li><a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "process-free-masterclass"]) ?>">PROCESS COHORT</a></li>

                <!-- <li><a href="form-rangeslider.html">Range Slider</a></li>
                <li><a href="form-datepicker.html">Datepicker</a></li> -->
            </ul>
        </div>
    </li>






    <!-- <li class="nav-item">
                    <a class="nav-link" href="page-messages.html">
                        <i class="icon ion-ios-chatboxes-outline"></i>
                        <span>Messages</span>

                    </a>
                    <div class="sub-item">
                        <ul>
                            <li><a href="form-elements.html">Registered User</a></li>
                            <li><a href="form-layouts.html">Registered Courses</a></li>
                            <li><a href="form-validation.html">Form Validation</a></li>
                            <li><a href="form-wizards.html">Form Wizards</a></li>
                            <li><a href="form-editor.html">WYSIWYG Editor</a></li>
                            <li><a href="form-select2.html">Select2</a></li>
                            <li><a href="form-rangeslider.html">Range Slider</a></li>
                            <li><a href="form-datepicker.html">Datepicker</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="widgets.html">
                        <i class="icon ion-ios-analytics-outline"></i>
                        <span>Widgets</span>
                    </a>
                </li> -->
</ul>