<!-- Courses Section - Start
  ================================================== -->
<section id="csr" class="courses_section section_space_lg">
    <div class="container">
        <div class="section_heading">
            <div class="row align-items-center justify-content-lg-between">
                <div class="col col-lg-6">
                    <h2 class="heading_text mb-0">
                        Availaible Programs
                    </h2>
                </div>
                <div class="col col-lg-5">
                    <p class="heading_description mb-0 text-lg-end">
                        <!--  Dignissim enim sit amet venenatis urna cursus eget nunc. Egestas sed sed risus pretium quam vulputate-->
                    </p>
                </div>
            </div>
        </div>

        <div class="tabs_wrapper">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <button class="active" data-bs-toggle="tab" data-bs-target="#teb_hr" type="button" role="tab"
                        aria-selected="true">
                        <i class="fas fa-users"></i>
                        <span>Business Analysis</span>
                    </button>
                </li>


            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="teb_hr" role="tabpanel">
                    <div v-if="courses.length" class="row">
                        <div v-for="cou in courses " class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="#" data-cursor-text="View">
                                        <img :src="cou.program.banner" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">{{cou.program.title}}</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">${{cou.program.cost}}</span>

                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">

                                    </ul>
                                    <h3 class="item_title">
                                        <a href="">
                                            {{cou.program.title}}
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div v-else>
                        <p>
                            No program Available
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- Courses Section - End
  ================================================== -->


<script>
const listee = Vue.createApp({
    data() {
        return {
            courses: [],
        }
    },
    mounted() {
        this.getList();
    },
    methods: {
        getList() {

            axios.get("/app/get-all-programs").then(res => {
                if (res.status = 200) {
                    this.courses = res.data.data
                }
            }).catch(err => {

            });
        }
    },
});
listee.mount("#csr")
</script>