<section class="faq_section section_space_lg" id="faq">
        <div class="container">
            <div class="section_heading text-center mb-3">
                <div class="row justify-content-center">
                    <div class="col col-lg-7">
                        <h2 class="heading_text mb-0">
                            Frequently Asked Questions
                        </h2>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col col-lg-10">
                    <div class="accordion" id="faq_accordion">
                        <div class="accordion-item">
                            <div class="accordion-button" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_one" aria-expanded="true">
                                What topics do your training programs cover
                            </div>
                            <div id="collapse_one" class="accordion-collapse collapse show" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        Our training programs cover business analysis work experience programs and certification programs
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_two" aria-expanded="false">
                                How long are your training sessions?
                            </div>
                            <div id="collapse_two" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        Our training sessions are mostly 2-4 hour long depending on the program you sign up for </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_three" aria-expanded="false">
                                Can you customize training programs to fit our specific needs?
                            </div>
                            <div id="collapse_three" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        Our personalized 1 on 1 support program is customized to help job seekers land a business analysis job in canada </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_four" aria-expanded="false">
                                What qualifications and expertise do your trainers have?
                            </div>
                            <div id="collapse_four" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        We each have over 8 years experience in business analysis working for the biggest companies in Canada and US </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_fivev" aria-expanded="false">
                                How much do your training programs cost?
                            </div>
                            <div id="collapse_fivev" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        Our training programs costs range from 1000-5000 USD depending on what you want </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_five" aria-expanded="false">
                                Do you offer online or in-person training?
                            </div>
                            <div id="collapse_five" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        All our training programs are online </p>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_fiver" aria-expanded="false">
                                Can we see a sample or demo of your training content?
                            </div>
                            <div id="collapse_fiver" class="accordion-collapse collapse" data-bs-parent="#faq_accordion">
                                <div class="accordion-body">
                                    <p class="mb-0">
                                        Our training content demo are under thé couse schedule-1 minute demo </p>
                                </div>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </section>