

<!-- Newslatter Section - Start
  ================================================== -->
  <section id="newsletter" class="newslatter_section">
    <div class="container">
        <div class="newslatter_box" style="background-image: url('assets/images/shape/shape_img_6.svg');">
            <div class="row justify-content-center">
                <div class="col col-lg-6">
                    <div class="section_heading text-center">
                        <h2 class="heading_text">
                            Subscribe Now Forget 20% Discount Every Courses
                        </h2>
                        <p class="heading_description mb-0">
                            Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus. Sed magna purus, fermentum eu
                        </p>
                    </div>
                    <form action="#">
                        <div class="form_item m-0">
                            <input type="email" name="email" placeholder="Your Email">
                            <button type="submit" class="btn btn_dark">
                                <span>
                                    <small>Subsctibe</small>
                                    <small>Subsctibe</small>
                                </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Newslatter Section - End
  ================================================== -->


  <script>
    const newsletter = Vue.createApp({
        data() {
            return {
                news: ""
            }
        },

        methods: {
            name() {
                
            }
        },
    });

    const letter = newsletter.mount("#newsletter")

  </script>