<!-- Newslatter Section - Start
  ================================================== -->
<section id="newsletter" class="newslatter_section">
    <div class="container">
        <div class="newslatter_box" style="background-image: url('assets/images/shape/shape_img_6.svg');">
            <div class="row justify-content-center">
                <div class="col col-lg-6">
                    <div class="section_heading text-center">
                        <h2 class="heading_text">
                            Subscribe Now To Get Best Deals
                        </h2>
                        <p class="heading_description mb-0">
                            <!--  Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus. Sed magna purus, fermentum eu-->
                        </p>
                    </div>
                    <!--    <form action="#"> -->
                    <div class="form_item m-0">
                        <input type="email" v-model="newsletter_email" name="email" placeholder="Your Email">
                        <button type="submit" @click="sendNewsLetter()" class="btn btn_dark">
                            <span>
                                <small>Subsctibe</small>
                                <small>Subsctibe</small>
                            </span>
                        </button>
                    </div>
                    <!--   </form> -->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Newslatter Section - End
  ================================================== -->


<script>
    const newsletter = Vue.createApp({
        data() {
            return {
                newsletter_email: "",
            }
        },

        methods: {
            sendNewsLetter() {

                if (this.newsletter_email == "") {
                    this.$toast.open({
                        message: "Email field cannot be empty",
                        type: "error",
                        position: "top-right",
                        duration: 30000,
                        dismissible: true

                    });

                } else {
                    let formData = new FormData();
                    formData.append("email", this.newsletter_email);
                    axios.post("/app/join-news-letter", formData).then(res => {
                        if (res.status == 201) {
                            this.$toast.open({
                                message: "we will be in touch as soon as posible ",
                                type: "success",
                                position: "top-right",
                                duration: 30000,
                                dismissible: true
                            })
                            this.newsletter_email = "";

                        }
                    }).catch(err => {
                        this.$toast.open({
                            message: err.response.data.message,
                            type: "error",
                            position: "top-right",
                            duration: 30000,
                            dismissible: true
                        });
                    });
                }
            }
        },
    });
    newsletter.use(VueToast.ToastPlugin);
    const letter = newsletter.mount("#newsletter");
</script>