<div id="modalQ<?= $course->getId() ?>" class="modal fade">
    <div class="modal-dialog modal-dialog-vertical-center" role="document">
        <div class="modal-content bd-0 tx-14">
            <div class="modal-header">
                <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">
                    Quiz </h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body pd-25">

                <div class="card card-body">
                    <div class="row">

                        <div v-for="list in quizList" class="col col-lg-12">

                            <p>
                                {{list.questions[quizCountInit].question}}

                            </p>
                            <div class="row mb-12">
                                <div class="col col-lg-12">
                                    <div v-for="(ans, index) in list.questions[quizCountInit].answer"
                                        class="checkbox_item">
                                        <input id="checkbox_design" v-bind:name="list.questions[quizCountInit].id"
                                            type="radio">
                                        <label for="checkbox_design"><span>{{ans.answerText}}</span></label>
                                    </div>

                                </div>

                            </div>



                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">

                <button v-if="quizCountInit != 0" @click="quizPreviousPage()" type="button"
                    class="btn btn-primary">Previous</button>
                <button v-if="quizCountInit == (questionCount - 1)" class="btn btn-success">Submit</button>
                <button v-else @click="quizNextPage()" type="button" class="btn btn-secondary">Next</button>

            </div>
        </div>
    </div><!-- modal-dialog -->
</div><!-- modal -->