<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
    <div class="panel-heading panel-collapse-trigger">
        <h4 class="panel-title">Menu</h4>
    </div>
    <div class="panel-body list-group">
        <ul class="list-group list-group-menu">
            <li class="list-group-item active"><a class="link-text-color" href="<?= $this->url("internship", ["controller" => "internship", "action" => "dashboard"]) ?>">Dashboard</a></li>
            <!-- <li class="list-group-item"><a class="link-text-color" href="">Class</a></li> -->
            <li class="list-group-item"><a class="link-text-color" href="">Course</a></li>
            <li class="list-group-item"><a class="link-text-color" href="">Assignment</a></li>
            <li class="list-group-item"><a class="link-text-color" href=""><span>Quiz</span></a></li>
            <li class="list-group-item"><a class="link-text-color" href=""><span>Tools</span></a></li>
        </ul>
    </div>
</div>