<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
    <div class="panel-heading panel-collapse-trigger">
        <h4 class="panel-title">My  <?= $title ?></h4>
    </div>
    <div class="panel-body list-group">
        <ul class="list-group list-group-menu">
            <li class="list-group-item"><a class="link-text-color" href="website-student-dashboard.html">Dashboard</a></li>
            <li class="list-group-item active"><a class="link-text-color" href="website-student-courses.html">My Courses</a></li>
            <li class="list-group-item"><a class="link-text-color" href="website-student-profile.html">Profile</a></li>
            <li class="list-group-item"><a class="link-text-color" href="website-student-messages.html">Messages</a></li>
            <li class="list-group-item"><a class="link-text-color" href="login.html"><span>Logout</span></a></li>
        </ul>
    </div>
</div>