<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand navbar-brand-logo">
            <a class="svg" href="<?= $this->url("home") ?>">
                <img width="143" height="42" src="/assets/images/oie_3QNUOMetbJh7.png" alt="Terces - Online Learning Platform"></a>
            </a>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-nav">
        <ul class="nav navbar-nav navbar-nav-margin-left">
            <li class="dropdown">
                <a href="<?= $this->url("internship") ?>">Board Home</a>

            </li>
            <!--    <li>
                <a href="<?= $this->url("internship", ["controller" => "classes", "action" => "hallway"]) ?>">Classes </a> 

            </li> -->
            <li>
                <a href="<?= $this->url("internship", ["controller" => "courses", "action" => "course"]) ?>">My Course</a>

            </li>
           <!-- <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instructor <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="website-instructor-dashboard.html">Dashboard</a></li>
                    <li><a href="website-instructor-courses.html">My Courses</a></li>
                    <li><a href="website-instructor-course-edit-course.html">Edit Course</a></li>
                    <li><a href="website-instructor-earnings.html">Earnings</a></li>
                    <li><a href="website-instructor-statement.html">Statement</a></li>
                    <li><a href="website-instructor-messages.html">Messages</a></li>
                    <li><a href="website-instructor-profile.html">Private Profile</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">UI <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="essential-buttons.html">Buttons</a></li>
                    <li><a href="essential-icons.html">Icons</a></li>
                    <li><a href="essential-progress.html">Progress</a></li>
                    <li><a href="essential-grid.html">Grid</a></li>
                    <li><a href="essential-forms.html">Forms</a></li>
                    <li><a href="essential-tables.html">Tables</a></li>
                    <li><a href="essential-tabs.html">Tabs</a></li>
                </ul>
            </li> -->
        </ul>
        <div class="navbar-right">
            <ul class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
                <!-- user -->
                <li class="dropdown user active">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/intern/images/people/110/guy-6.jpg" alt="" class="img-circle" /> User<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                     <!--   <li class="active"><a href="website-student-dashboard.html"><i class="fa fa-bar-chart-o"></i> Dashboard</a></li>
                        <li><a href="website-student-courses.html"><i class="fa fa-mortar-board"></i> My Courses</a></li>
                        <li><a href="website-student-profile.html"><i class="fa fa-user"></i> Profile</a></li> -->
                        <li><a href="<?= $this->url("logout") ?>"><i class="fa fa-sign-out"></i> Logout</a></li>
                    </ul>
                </li>
                <!-- // END user -->
            </ul>
            <a href="<?= $this->url("logout") ?>" class="navbar-btn btn btn-primary">Logout</a>
        </div>
    </div>
    <!-- /.navbar-collapse -->

</div>