<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
    <div class="panel-heading panel-collapse-trigger">
        <h4 class="panel-title"> Menu </h4>
    </div>
    <div class="panel-body list-group">
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge pull-right"> </span>
                <a class="list-group-link" href="">Dashboard</a>
            </li>
            <!--   <li class="list-group-item active">
                <span class="badge pull-right">30+</span>
                <a class="list-group-link" href="">Programming</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">40+</span>
                <a class="list-group-link" href="">WordPress</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">60+</span>
                <a class="list-group-link" href="index.html">Workflow</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">15+</span>
                <a class="list-group-link" href="index.html">HTML</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">25+</span>
                <a class="list-group-link" href="index.html">CSS</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">35+</span>
                <a class="list-group-link" href="index.html">iOS</a>
            </li>
            <li class="list-group-item">
                <span class="badge pull-right">20+</span>
                <a class="list-group-link" href="index.html">Free</a>
            </li> -->
        </ul>
    </div>
</div>