<?php
echo $this->headtitle("Active List of programs");

?>
<div class="section-wrapper mg-t-20">
    <label class="section-title">Sudcribed Users</label>
    <p class="mg-b-20 mg-sm-b-40">Users and and programs they subscibe to</p>

    <div class="table-responsive">
        <table class="table table-bordered table-colored table-success">
            <thead>
                <tr>

                    <th class="wd-35p">Program</th>
                    <th class="wd-35p">Customer</th>
                    <th class="wd-20p">Status</th>
                    <th class="wd-10p"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $key => $value) : ?>
                <tr>

                    <td><strong>Program :</strong> <?= $value["program"]["title"] ?></td>
                    <td>
                        <strong>Fullname :</strong><?= $value["user"]["fullname"] ?><br>
                        <strong>Email :</strong><?= $value["user"]["email"] ?><br>

                    </td>
                    <td><?= $value["status"]["status"] ?></td>
                    <td><a href=""><i class="fa fa-eye"></i></a> |
                        <a href=""><i class="icon ion-share "></i></a> |
                        <a href=""><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>

            </tbody>
        </table>
    </div><!-- table-responsive -->

</div><!-- section-wrapper -->