<?php $this->headTitle("Create User"); ?>

<div id="createUser" class="row row-sm mg-t-20">
    <div class="col-lg-6">
        <div class="section-wrapper">
            <label class="section-title">Create User</label>
            <p class="mg-b-20 mg-sm-b-40">A basic form where labels are aligned in left.</p>

            <div class="form-layout form-layout-4">
                <div class="row">
                    <label class="col-sm-4 form-control-label">Fullname: <span class="tx-danger">*</span></label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" v-model="fullname" class="form-control">
                    </div>
                </div><!-- row -->
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label">Email: <span class="tx-danger">*</span></label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" v-model="email" class="form-control">
                    </div>
                </div>
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label">Assign To Cohort <span class="tx-danger">*</span></label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="checkbox" @click="toggleCheckbox()" :checked="acohort" class="form-control">
                    </div>
                </div>
                <div v-if="acohort" class="row mg-t-20">
                    <label class="col-sm-4 form-control-label">Select A Cohort <span class="tx-danger">*</span></label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">

                        <select v-if="cohort.length" rows="2" class="form-control" v-model="selectedCohort">
                            <option v-for="coh in cohort" :value="coh.id">{{coh.cohort}}</option>
                        </select>
                    </div>
                </div>
                <div class="form-layout-footer mg-t-30">
                    <button @click="createUser()" class="btn btn-primary bd-0">Submit Form</button>
                    <button class="btn btn-secondary bd-0">Cancel</button>
                </div><!-- form-layout-footer -->
            </div><!-- form-layout -->
        </div><!-- section-wrapper -->
    </div><!-- col-6 -->
    <div class="col-lg-6 mg-t-20 mg-lg-t-0">
        <div class="section-wrapper">
            <label class="section-title">Right Label Alignment</label>
            <p class="mg-b-20 mg-sm-b-40">A basic form where labels are aligned in right.</p>
            <div class="form-layout form-layout-5">
                <div class="row">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Firstname:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter firstname">
                    </div>
                </div><!-- row -->
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Lastname:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter lastname">
                    </div>
                </div>
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Email:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <input type="text" class="form-control" placeholder="Enter email address">
                    </div>
                </div>
                <div class="row mg-t-20">
                    <label class="col-sm-4 form-control-label"><span class="tx-danger">*</span> Address:</label>
                    <div class="col-sm-8 mg-t-10 mg-sm-t-0">
                        <textarea rows="2" class="form-control" placeholder="Enter your address"></textarea>
                    </div>
                </div><!-- row -->
                <div class="row mg-t-30">
                    <div class="col-sm-8 mg-l-auto">
                        <div class="form-layout-footer">
                            <button class="btn btn-primary bd-0">Submit Form</button>
                            <button class="btn btn-secondary bd-0">Cancel</button>
                        </div><!-- form-layout-footer -->
                    </div><!-- col-8 -->
                </div>
            </div><!-- form-layout -->
        </div><!-- section-wrapper -->
    </div><!-- col-6 -->
</div><!-- row -->

<script>
    const createUserApp = Vue.createApp({
        data() {
            return {
                fullname: "",
                email: "",
                cohort: "",
                acohort: false,
                selectedCohort: '',
            }
        },

        mounted() {
            this.getCohort()
        },

        methods: {
            toggleCheckbox() {
                this.acohort = !this.acohort;
            },
            getCohort() {
                axios.get("/get-internship-cohort").then((result) => {
                    if (result.status == 200) {
                        this.cohort = result.data.data;
                    }
                }).catch((err) => {

                });

            },

            createUser() {
                if (this.fullname == "" || this.email == "") {
                    Swal.fire({
                        icon: 'error',
                        title: 'Required Field',
                        text: "A required feild is empty"
                    });
                } else {
                    let formData = new FormData();
                    formData.append("fullname", this.fullname);
                    formData.append("email", this.email);
                    formData.append("isCohort", this.acohort);
                    formData.append("cohort", this.selectedCohort);
                    // console.log(this.acohort);
                    // axios.post("/admin/create-user", formData).then((result) => {
                    //     if (result.status == 201) {
                    //         Swal.fire({
                    //             icon: 'success',
                    //             title: 'User Created',
                    //             text: "User has been successfully created",

                    //         }).then((result) => {
                    //             window.location.reload();
                    //         }).catch((err) => {

                    //         });
                    //     }
                    // }).catch((err) => {

                    // });
                }
            }


        },


    });
    createUserApp.mount("#createUser");
</script>