<?php

use Admin\Controller\InternshipController;

 echo $this->headtitle("Internship Board"); ?>
<div id="ddd">
    <div class="dash-headline-two">
        <div>
            <h4 class="tx-inverse mg-b-5">Good morning, Katherine!</h4>
            <p class="mg-b-0">Today is March 20, 2018</p>
        </div>
        <div class="d-h-t-right">
            <div class="summary-item">
                <h1>$1,433</h1>
                <span>Earnings<br>for today</span>
            </div>
            <div class="summary-item">
                <h1>$296</h1>
                <span>Expenses<br>for today</span>
            </div>
        </div>
    </div><!-- dash-headline-two -->

    <div class="nav-statistics-wrapper">
        <nav class="nav">
            <a href="" class="nav-link active">Overview</a>
            <a href="" class="nav-link">Employee</a>
            <a href="" class="nav-link">Products</a>
            <a href="" class="nav-link">Misc</a>
        </nav>
        <nav class="nav">
            <a href="" class="nav-link">Today</a>
            <a href="" class="nav-link active">This Week</a>
            <a href="" class="nav-link">This Month</a>
        </nav>
    </div><!-- nav-statistics-wrapper -->

    <div class="row row-statistics mg-b-30">
        <div class="col-md-5">
            <h1 class="tx-inverse tx-56 tx-lato tx-bold">34,100</h1>
            <h6 class="tx-15 tx-inverse tx-bold mg-b-20">Total hours spent (7 days)</h6>
            <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem</p>
            <p class="tx-12">
                <a href="">View Details</a>
                <a href="">Edit Settings</a>
            </p>
        </div><!-- col-5 -->
        <div class="col-md-7 mg-t-20 mg-md-t-0">
            <canvas id="chartBar1" height="280"></canvas>
        </div><!-- col-7 -->
    </div><!-- row -->

    <hr>

    <div class="report-summary-header">
        <div>
            <h4 class="tx-inverse mg-b-3">Overall Report Summary</h4>
            <p class="mg-b-0"><i class="icon ion-calendar mg-r-3"></i> January 01, 2018 - January 31, 2018</p>
        </div>
        <div>
            <a href="" class="btn btn-secondary"><i class="icon ion-ios-clock-outline tx-22"></i> Activity Logs</a>
            <a href="" class="btn btn-secondary"><i class="icon ion-ios-gear-outline tx-24"></i> Edit Settings</a>
        </div>
    </div><!-- d-flex -->




    <div class="row no-gutters dashboard-chart-one">
        <div class="col-md-4 col-lg">
            <div class="card card-total">
                <div>
                    <h1>{{totalInternRegistered}}</h1>
                    <p>Total Intern</p>
                </div>
                <div>
                    <div class="tx-24 mg-b-10 tx-center op-5">
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-600"></i>
                        <i class="icon ion-man tx-gray-400"></i>
                        <i class="icon ion-man tx-gray-400"></i>
                        <i class="icon ion-man tx-gray-400"></i>
                        <i class="icon ion-man tx-gray-400"></i>
                    </div>
                    <!--    <label>Female (66%)</label>
                    <div class="progress mg-b-10">
                        <div class="progress-bar bg-primary progress-bar-xs wd-65p" role="progressbar" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <label>Male (34%)</label>
                    <div class="progress">
                        <div class="progress-bar bg-danger progress-bar-xs wd-35p" role="progressbar" aria-valuenow="34" aria-valuemin="0" aria-valuemax="100"></div>
                    </div> -->
                </div>
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-md-4 col-lg">
            <div class="card card-total">
                <div>
                    <h1>{{totalActiveIntern}}</h1>
                    <p>Total Active</p>
                </div>
                <div>
                    <div class="tx-16 mg-b-15 tx-center op-5">
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-600"></i>
                        <i class="icon ion-cube tx-gray-400"></i>
                        <i class="icon ion-cube tx-gray-400"></i>
                    </div>
                    <!-- <label>Digital products (85%)</label>
                    <div class="progress mg-b-10">
                        <div class="progress-bar bg-success progress-bar-xs wd-85p" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <label>Non-digital products (15%)</label>
                    <div class="progress">
                        <div class="progress-bar bg-warning progress-bar-xs wd-15p" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                    </div> -->
                </div>
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-md-4 col-lg">
            <div class="card card-total">
                <div>
                    <h1>30</h1>
                    <p>Total Franchise</p>
                </div>
                <div>
                    <div class="tx-22 mg-b-10 tx-center op-5">
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-600"></i>
                        <i class="icon ion-location tx-gray-400"></i>
                        <i class="icon ion-location tx-gray-400"></i>
                        <i class="icon ion-location tx-gray-400"></i>
                    </div>
                    <label>Local (75%)</label>
                    <div class="progress mg-b-10">
                        <div class="progress-bar bg-purple progress-bar-xs wd-75p" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                    </div><!-- progress -->

                    <label>International (25%)</label>
                    <div class="progress">
                        <div class="progress-bar bg-pink progress-bar-xs wd-25p" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                    </div><!-- progress -->
                </div>
            </div><!-- card -->
        </div><!-- col -->
        <div class="col-md col-lg-4">
            <div class="card card-revenue">
                <h6>Monthly Revenue</h6>
                <p>Calculated every 15th of the month</p>
                <h1>$32,500 <span class="tx-success">1.4% up</span></h1>
                <div id="rs3" class="ht-50 ht-sm-70 mg-r--1"></div>
                <label>Last month: <span>$79,554</span></label>
            </div><!-- card -->
        </div><!-- col-4 -->
    </div><!-- row -->

    <hr>

    <div class="row row-sm mg-t-20">
        <div class="card card-body pd-25 tx-center col-lg-4 mg-t-20 mg-lg-t-0">
            <div class="card-icon-wrapper success">
                <i class="icon ion-ios-upload"></i>
            </div><!-- icon-wrapper -->
            <h4 class="tx-gray-800 mg-b-25">Upload Training</h4>
            
            <a href="<?= $this->url("admin-general", ["controller"=>"admin-intern", "action"=>"upload-video" ]) ?>" class="btn btn-success btn-block">Browse Articles</a>
        </div><!-- card -->


        <div class="card card-body pd-25 tx-center col-lg-4 mg-t-20 mg-lg-t-0">
            <div class="card-icon-wrapper success">
                <i class="icon ion-ios-paper-outline"></i>
            </div><!-- icon-wrapper -->
            <h4 class="tx-gray-800 mg-b-25">Knowledge Base</h4>
            <p class="mg-b-25">Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.</p>
            <a href="" class="btn btn-success btn-block">Browse Articles</a>
        </div><!-- card -->

        <div class="card card-body pd-25 tx-center col-lg-4 mg-t-20 mg-lg-t-0">
            <div class="card-icon-wrapper success">
                <i class="icon ion-ios-paper-outline"></i>
            </div><!-- icon-wrapper -->
            <h4 class="tx-gray-800 mg-b-25">Knowledge Base</h4>
            <p class="mg-b-25">Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.</p>
            <a href="" class="btn btn-success btn-block">Browse Articles</a>
        </div><!-- card -->
    </div><!-- row -->
    <hr>


</div>
<script>
    const appsss = Vue.createApp({
        data() {
            return {
                assignments: [],
                resos: [],
                totalInternRegistered: 0,
                totalActiveIntern: 0,
            }
        },
        mounted() {
            this.totalRegistered();
            this.totalActive();
        },
        methods: {
            getAssignment() {

            },
            totalRegistered() {
                axios.get("/admins/admin-intern/total-registered").then((result) => {
                    if (result.status == 200) {
                        this.totalInternRegistered = result.data.total;
                    }
                }).catch((err) => {

                });
            },

            totalActive() {
                axios.get("/admins/admin-intern/total-active").then((result) => {
                    if (result.status == 200) {
                        this.totalActiveIntern = result.data.total;
                    }
                }).catch((err) => {

                });
            },
        },
    });
    appsss.mount("#ddd")
</script>