<?php echo $this->headtitle("Registered User List");
// var_dump($data);
?>


<div class="section-wrapper mg-t-20">
    <label class="section-title">Sudcribed Users</label>
    <p class="mg-b-20 mg-sm-b-40">Users and and programs they subscibe to</p>

    <div class="table-responsive">
        <table class="table table-bordered table-colored table-purple">
            <thead>

                <tr>
                    <th class="wd-10p">ID</th>
                    <th class="wd-35p">Name</th>
                    <th class="wd-35p">Role</th>
                    <th class="wd-20p">Salary</th>
                    <th class="wd-10p">Action</th>
                </tr>

            </thead>
            <tbody>
                <?php foreach ($data as $key => $da) : ?>
                    <tr>
                        <th scope="row"><?= $da["id"] ?></th>
                        <td><strong>Fullname : </strong><?= $da["fullname"] ?> <br>
                            <strong>Email : </strong> <?= $da["email"] ?>


                        </td>
                        <td><?= $da["role"]["name"] ?></td>
                        <td><?= $this->dateformat($da["registrationDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?>
                        </td>
                        <td>
                            <div class="row">
                                <button class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></button>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div><!-- table-responsive -->

</div><!-- section-wrapper -->