<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use General\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Terces Academy')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])

        ->prependStylesheet($this->basePath("/slim/lib/SpinKit/css/spinkit.css"))
        ->prependStylesheet($this->basePath('/slim/css/slim.css'))
        ->prependStylesheet($this->basePath('/slim/lib/rickshaw/css/rickshaw.min.css'))
        ->prependStylesheet($this->basePath('/slim/lib/chartist/css/chartist.css'))
        ->prependStylesheet($this->basePath('/slim/lib/Ionicons/css/ionicons.css'))
        ->prependStylesheet($this->basePath('/slim/lib/font-awesome/css/font-awesome.css'))
    ?>



    <link rel="stylesheet" href="/slim/css/slim.css">

    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://checkout.flutterwave.com/v3.js"></script>


    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <div class="slim-header">
        <div class="container">
            <div class="slim-header-left">
                <h2 class="slim-logo"><a href="index.html">slim<span>.</span></a></h2>

                <div class="search-box">
                    <input type="text" class="form-control" placeholder="Search">
                    <button class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div><!-- search-box -->
            </div><!-- slim-header-left -->
            <div class="slim-header-right">
                <div class="dropdown dropdown-a">
                    <a href="" class="header-notification" data-toggle="dropdown">
                        <i class="icon ion-ios-bolt-outline"></i>
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-menu-header">
                            <h6 class="dropdown-menu-title">Activity Logs</h6>
                            <div>
                                <a href="">Filter List</a>
                                <a href="">Settings</a>
                            </div>
                        </div><!-- dropdown-menu-header -->
                        <div class="dropdown-activity-list">
                            <div class="activity-label">Today, December 13, 2017</div>
                            <div class="activity-item">
                                <div class="row no-gutters">
                                    <div class="col-2 tx-right">10:15am</div>
                                    <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                    <div class="col-8">Purchased christmas sale cloud storage</div>
                                </div><!-- row -->
                            </div><!-- activity-item -->
                            <div class="activity-item">
                                <div class="row no-gutters">
                                    <div class="col-2 tx-right">9:48am</div>
                                    <div class="col-2 tx-center"><span class="square-10 bg-danger"></span></div>
                                    <div class="col-8">Login failure</div>
                                </div><!-- row -->
                            </div><!-- activity-item -->
                            <div class="activity-item">
                                <div class="row no-gutters">
                                    <div class="col-2 tx-right">7:29am</div>
                                    <div class="col-2 tx-center"><span class="square-10 bg-warning"></span></div>
                                    <div class="col-8">(D:) Storage almost full</div>
                                </div><!-- row -->
                            </div><!-- activity-item -->
                            <div class="activity-item">
                                <div class="row no-gutters">
                                    <div class="col-2 tx-right">3:21am</div>
                                    <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                    <div class="col-8">1 item sold <strong>Christmas bundle</strong></div>
                                </div><!-- row -->
                            </div><!-- activity-item -->
                            <div class="activity-label">Yesterday, December 12, 2017</div>
                            <div class="activity-item">
                                <div class="row no-gutters">
                                    <div class="col-2 tx-right">6:57am</div>
                                    <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                    <div class="col-8">Earn new badge <strong>Elite Author</strong></div>
                                </div><!-- row -->
                            </div><!-- activity-item -->
                        </div><!-- dropdown-activity-list -->
                        <div class="dropdown-list-footer">
                            <a href="page-activity.html"><i class="fa fa-angle-down"></i> Show All Activities</a>
                        </div>
                    </div><!-- dropdown-menu-right -->
                </div><!-- dropdown -->
                <div class="dropdown dropdown-b">
                    <a href="" class="header-notification" data-toggle="dropdown">
                        <i class="icon ion-ios-bell-outline"></i>
                        <span class="indicator"></span>
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-menu-header">
                            <h6 class="dropdown-menu-title">Notifications</h6>
                            <div>
                                <a href="">Mark All as Read</a>
                                <a href="">Settings</a>
                            </div>
                        </div><!-- dropdown-menu-header -->
                        <div class="dropdown-list">
                            <!-- loop starts here -->
                            <a href="" class="dropdown-link">
                                <div class="media">
                                    <img src="http://via.placeholder.com/500x500" alt="">
                                    <div class="media-body">
                                        <p><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                                        <span>October 03, 2017 8:45am</span>
                                    </div>
                                </div><!-- media -->
                            </a>
                            <!-- loop ends here -->
                            <a href="" class="dropdown-link">
                                <div class="media">
                                    <img src="http://via.placeholder.com/500x500" alt="">
                                    <div class="media-body">
                                        <p><strong>Mellisa Brown</strong> appreciated your work <strong>The Social
                                                Network</strong></p>
                                        <span>October 02, 2017 12:44am</span>
                                    </div>
                                </div><!-- media -->
                            </a>
                            <a href="" class="dropdown-link read">
                                <div class="media">
                                    <img src="http://via.placeholder.com/500x500" alt="">
                                    <div class="media-body">
                                        <p>20+ new items added are for sale in your <strong>Sale Group</strong></p>
                                        <span>October 01, 2017 10:20pm</span>
                                    </div>
                                </div><!-- media -->
                            </a>
                            <a href="" class="dropdown-link read">
                                <div class="media">
                                    <img src="http://via.placeholder.com/500x500" alt="">
                                    <div class="media-body">
                                        <p><strong>Julius Erving</strong> wants to connect with you on your conversation
                                            with <strong>Ronnie Mara</strong></p>
                                        <span>October 01, 2017 6:08pm</span>
                                    </div>
                                </div><!-- media -->
                            </a>
                            <div class="dropdown-list-footer">
                                <a href="page-notifications.html"><i class="fa fa-angle-down"></i> Show All
                                    Notifications</a>
                            </div>
                        </div><!-- dropdown-list -->
                    </div><!-- dropdown-menu-right -->
                </div><!-- dropdown -->
                <div class="dropdown dropdown-c">
                    <a href="#" class="logged-user" data-toggle="dropdown">
                        <img src="http://via.placeholder.com/500x500" alt="">
                        <span>Katherine</span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <nav class="nav">
                            <a href="page-profile.html" class="nav-link"><i class="icon ion-person"></i> View
                                Profile</a>
                            <a href="page-edit-profile.html" class="nav-link"><i class="icon ion-compose"></i> Edit
                                Profile</a>
                            <a href="page-activity.html" class="nav-link"><i class="icon ion-ios-bolt"></i> Activity
                                Log</a>
                            <a href="page-settings.html" class="nav-link"><i class="icon ion-ios-gear"></i> Account
                                Settings</a>
                            <a href="page-signin.html" class="nav-link"><i class="icon ion-forward"></i> Sign Out</a>
                        </nav>
                    </div><!-- dropdown-menu -->
                </div><!-- dropdown -->
            </div><!-- header-right -->
        </div><!-- container -->
    </div><!-- slim-header -->

    <div class="slim-navbar">
        <div class="container">
            <ul class="nav">
                <li class="nav-item with-sub ">
                    <a class="nav-link" href="<?= $this->url("admin", ["action" => "index"]) ?>">
                        <i class="icon ion-ios-home-outline"></i>
                        <span>Dashboard</span>
                    </a>

                </li>

                <li class="nav-item with-sub mega-dropdown">
                    <a class="nav-link" href="<?= $this->url("admin", ["action" => "program-list"]) ?>">
                        <i class="icon ion-ios-filing-outline"></i>
                        <span>Programs</span>
                    </a>

                </li>

                <li class="nav-item with-sub">
                    <a class="nav-link" href="#" data-toggle="dropdown">
                        <i class="icon ion-ios-gear-outline"></i>
                        <span>Users</span>
                    </a>
                    <div class="sub-item">
                        <ul>
                            <li><a href="<?= $this->url("admin", ["action" => "user-list"]) ?>">Registered User</a></li>
                            <li><a href="form-layouts.html">Registered Courses</a></li>

                        </ul>
                    </div><!-- dropdown-menu -->
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="page-messages.html">
                        <i class="icon ion-ios-chatboxes-outline"></i>
                        <span>Messages</span>

                    </a>
                    <div class="sub-item">
                        <ul>
                            <li><a href="form-elements.html">Registered User</a></li>
                            <li><a href="form-layouts.html">Registered Courses</a></li>
                            <li><a href="form-validation.html">Form Validation</a></li>
                            <li><a href="form-wizards.html">Form Wizards</a></li>
                            <li><a href="form-editor.html">WYSIWYG Editor</a></li>
                            <li><a href="form-select2.html">Select2</a></li>
                            <li><a href="form-rangeslider.html">Range Slider</a></li>
                            <li><a href="form-datepicker.html">Datepicker</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="widgets.html">
                        <i class="icon ion-ios-analytics-outline"></i>
                        <span>Widgets</span>
                    </a>
                </li> -->
            </ul>
        </div><!-- container -->
    </div><!-- slim-navbar -->

    <div class="slim-mainpanel">
        <div class="container pd-t-50">
            <?= $this->content ?>

        </div><!-- container -->
    </div><!-- slim-mainpanel -->

    <div class="slim-footer">
        <div class="container">
            <p>Copyright <?= date("Y") ?> &copy; All Rights Reserved. Terces Academy</p>

        </div><!-- container -->
    </div><!-- slim-footer -->

    <script src="/slim/lib/jquery/js/jquery.js"></script>
    <script src="/slim/lib/popper.js/js/popper.js"></script>
    <script src="/slim/lib/bootstrap/js/bootstrap.js"></script>
    <script src="/slim/lib/jquery.cookie/js/jquery.cookie.js"></script>
    <script src="/slim/lib/chartist/js/chartist.js"></script>
    <script src="/slim/lib/d3/js/d3.js"></script>
    <script src="/slim/lib/rickshaw/js/rickshaw.min.js"></script>
    <script src="/slim/lib/jquery.sparkline.bower/js/jquery.sparkline.min.js"></script>

    <script src="/slim/js/ResizeSensor.js"></script>
    <script src="/slim/js/dashboard.js"></script>
    <script src="/slim/js/slim.js"></script>
</body>
<?= $this->inlineScript()
    ->prependFile($this->basePath('/slim/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/slim/js/jquery-3.5.1.min.js')) ?>


</html>