<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use General\Service\GeneralService;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Terces Academy')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('/assets/css/style.css'))
        ->prependStylesheet($this->basePath('/assets/css/vanilla-calendar.min.css'))
        ->prependStylesheet($this->basePath('assets/css/animate.css'))
        ->prependStylesheet($this->basePath('assets/css/cursor.css'))
        ->prependStylesheet($this->basePath('/assets/css/slick.css'))
        ->prependStylesheet($this->basePath('/assets/css/slick-theme.css'))
        ->prependStylesheet($this->basePath('/assets/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('/assets/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('/assets/css/bootstrap.min.css'))
    ?>



    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@3"></script>
    <link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@3/dist/theme-sugar.css" rel="stylesheet">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://checkout.flutterwave.com/v3.js"></script>


    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>

    <div class="page_wrapper">

        <!-- Back To Top - Start -->
        <div class="backtotop">
            <a href="#" class="scroll">
                <i class="far fa-arrow-up"></i>
            </a>
        </div>
        <!-- Back To Top - End -->

        <!-- Site Header - Start
================================================== -->
        <header class="site_header site_header_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col col-lg-3 col-5">
                        <div class="site_logo">
                            <a class="site_link" href="<?= $this->url("home") ?>">
                                <img width="143" height="42" src="/assets/images/oie_3QNUOMetbJh7.png" alt="Terces - Online Learning Platform">
                            </a>
                        </div>
                    </div>
                    <div class="col col-lg-6 col-2">
                        <nav class="main_menu navbar navbar-expand-lg">
                            <div class="main_menu_inner collapse navbar-collapse justify-content-center" id="main_menu_dropdown">
                                <ul class="main_menu_list unordered_list_center">
                                    <li><a class="nav-link" href="<?php echo  $this->url("home"); ?>">Home</a></li>
                                    <li><a class="nav-link" href="<?php echo $this->url("application", ["action" => "about"]) ?>">About
                                            Us</a></li>

                                    <li class="dropdown">
                                        <a class="nav-link" href="#" id="pages_submenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Programs
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="pages_submenu">
                                            <li><a href="<?= $this->url("application", ["action" => "business-analysis-program"]) ?>"><?= GeneralService::GENERAL_TRAINING_WORK_EXPERIENCE ?>
                                                </a></li>

                                            <li><a href="<?= $this->url("application", ["action" => "internship"]) ?>"><?= GeneralService::GENERAL_INTERNSHIP_ON_JOB_TRAINING ?></a></li>

                                             <!--   <li><a href="<?= $this->url("application", ["action" => "business-certificate-program"]) ?>"><?= GeneralService::GENERAL_TRAINING_CERTIFICATE_PROGRAM ?>
                                                </a></li>


                                        <li><a href="<?= $this->url("application", ["action" => "one-on-one-interview-prep"]) ?>"><?= GeneralService::GENERAL_TRAINING_INTERVIEW_PREP ?>
                                                </a></li> -->

                                            <li><a href="<?= $this->url("application", ["action" => "career-service"]) ?>">Career
                                                    Service</a></li>

                                        </ul>
                                    </li>
                                    <!--   <li><a class="nav-link"
                                            href="">Free
                                            Training</a></li> -->
                                    <li><a class="nav-link" href="<?= $this->url("application", ["action" => "about"]) . "#faq" ?>">FAQ</a>
                                    </li>


                                    <li><a class="nav-link" href="<?= $this->url("application", ["action" => "contact"]) ?>">Contact</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                    <div class="col col-lg-3 col-5">
                        <ul class="header_btns_group unordered_list_end">
                            <li>
                                <button class="mobile_menu_btn" type="button" data-bs-toggle="collapse" data-bs-target="#main_menu_dropdown" aria-controls="main_menu_dropdown" aria-expanded="false" aria-label="Toggle navigation">
                                    <i class="far fa-bars"></i>
                                </button>
                            </li>
                            <?php

                            if ($this->identity()) : ?>
                                <li>
                                    <a class="btn border_dark" href="<?= $this->url("login") ?>">
                                        <span>
                                            <small>My Acc.</small>
                                            <small>My Acc.</small>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="btn border_dark" href="<?= $this->url("logout") ?>">
                                        <span>
                                            <small>Logout</small>
                                            <small>Logout</small>
                                        </span>
                                    </a>
                                </li>
                            <?php else : ?>
                                <li>
                                    <a class="btn border_dark" href="<?= $this->url("login") ?>">
                                        <span>
                                            <small>Login</small>
                                            <small>Login</small>
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="btn btn_dark" href="<?= $this->url("register") ?>">
                                        <span>
                                            <small>Sign Up</small>
                                            <small>Sign Up</small>
                                        </span>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <!-- Site Header - End
================================================== -->

        <!-- Main Body - Start
================================================== -->
        <main class="page_content">


            <?php
            $flashMessenger = $this->flashMessenger()
                ->setMessageOpenFormat('<div%s  role="alert">
                <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
     <ul><li>')

                ->setMessageCloseString('</div>');
            ?>
            <?php echo $flashMessenger->render('error', ['alert', 'alert-dismissable', 'alert-danger']); ?>
            <?php echo $flashMessenger->render('info', ['alert', 'alert-dismissable', 'alert-info']); ?>
            <?php echo $flashMessenger->render('default', ['alert', 'alert-dismissable', 'alert-warning']); ?>
            <?php echo $flashMessenger->render('success', ['alert', 'alert-dismissable', 'alert-success']); ?>
            <?= $this->content ?>
        </main>
        <!-- Main Body - End
================================================== -->

        <!-- Site Footer - Start
================================================== -->
        <footer class="site_footer">
            <div class="footer_widget_area">
                <div class="container">
                    <div class="row">
                        <div class="col col-lg-4 col-md-6 col-sm-6">
                            <div class="footer_widget">
                                <div class="site_logo">
                                    <a class="site_link" href="">
                                        <img src="/assets/images/oie_3QNUOMetbJh7.png" alt="Terces - Online Learning Platform">
                                    </a>
                                </div>
                                <p>
                                    <!--  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat -->
                                </p>
                                <ul class="social_links unordered_list">
                                    <li>
                                        <a href="https://web.facebook.com/people/TercesJobs/100090477406059/"><i class="fab fa-facebook-f"></i></a>
                                    </li>
                                    <!--    <li>
                                        <a href="#!"><i class="fab fa-youtube"></i></a>
                                    </li> -->
                                    <li>
                                        <a href="https://www.tiktok.com/@tercesjobs?is_from_webapp=1&sender_device=pc"><i class="fab fa-tiktok"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/company/tercesjobs/"><i class="fab fa-linkedin"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/tercesjobs/"><i class="fab fa-instagram"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://t.me/TercesJobs/1"><i class="fab fa-telegram"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col col-lg-6">
                            <div class="row">
                                <div class="col col-md-4 col-sm-4">
                                    <div class="footer_widget">
                                        <h3 class="footer_widget_title">Links</h3>
                                        <ul class="page_list unordered_list_block">
                                            <li>
                                                <a href="">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">About</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Programs</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Free Training</span>
                                                </a>
                                            </li>
                                            <?php if ($this->identity() != NULL) :
                                                if ($this->identity()->getRole()->getId() == 1000) : ?>
                                                    <li>
                                                        <a href="<?= $this->url("admin") ?>">
                                                            <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                            <span class="item_text">Admin</span>
                                                        </a>
                                                    </li>
                                            <?php

                                                endif;
                                            endif; ?>
                                            <li>
                                                <a href="">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Contact</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-6 col-md-6 col-sm-6">
                                    <div class="footer_widget">
                                        <h3 class="footer_widget_title">Program</h3>
                                        <ul class="page_list unordered_list_block">
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text"><?= GeneralService::GENERAL_TRAINING_WORK_EXPERIENCE ?></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text"><?= GeneralService::GENERAL_TRAINING_CERTIFICATE_PROGRAM ?></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text"><?= GeneralService::GENERAL_TRAINING_INTERVIEW_PREP ?></span>
                                                </a>
                                            </li>

                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="copyright_widget">
                <div class="container">
                    <p class="copyright_text text-center mb-0">
                        <a href="#"></a> © <b> Terces Academy </b></b> All rights reserved Copyrights <?php date("Y") ?>
                    </p>
                </div>
            </div>
        </footer>
        <!-- Site Footer - End
================================================== -->

    </div>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/bootstrap-dropdown-ml-hack.js"></script>

    <!-- animation - jquery include -->
    <script src="/assets/js/cursor.js"></script>
    <script src="/assets/js/wow.min.js"></script>
    <script src="/assets/js/tilt.min.js"></script>
    <script src="/assets/js/parallax.min.js"></script>
    <script src="/assets/js/parallax-scroll.js"></script>

    <!-- Carousel - Jquery Include -->
    <script src="/assets/js/slick.min.js"></script>

    <!-- Video & Image Popup - Jquery Include -->
    <script src="/assets/js/magnific-popup.min.js"></script>

    <!-- Counter Up - Jquery Include -->
    <script src="/assets/js/waypoint.js"></script>
    <script src="/assets/js/counterup.min.js"></script>

    <!-- Countdown Timer - jquery include -->
    <script src="/assets/js/countdown.js"></script>

    <!-- Vanilla Calendar - Jquery Include -->
    <script src="/assets/js/vanilla-calendar.min.js"></script>

    <!-- Custom - Jquery Include -->
    <script src="/assets/js/main.js"></script>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>

</html>