<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Terces Academy')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('/assets/css/style.css'))
        ->prependStylesheet($this->basePath('/assets/css/vanilla-calendar.min.css'))
        ->prependStylesheet($this->basePath('assets/css/animate.css'))
        ->prependStylesheet($this->basePath('assets/css/cursor.css'))
        ->prependStylesheet($this->basePath('/assets/css/slick.css'))
        ->prependStylesheet($this->basePath('assets/css/slick-theme.css'))
        ->prependStylesheet($this->basePath('/assets/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('/assets/css/fontawesome.css'))
        ->prependStylesheet($this->basePath('/assets/css/bootstrap.min.css'))
?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>

    <div class="page_wrapper">

        <!-- Back To Top - Start -->
        <div class="backtotop">
            <a href="#" class="scroll">
                <i class="far fa-arrow-up"></i>
            </a>
        </div>
        <!-- Back To Top - End -->

        <!-- Site Header - Start
================================================== -->
        <header class="site_header site_header_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col col-lg-3 col-5">
                        <div class="site_logo">
                            <a class="site_link" href="<?= $this->url("home") ?>">
                                <img width="143" height="42" src="assets/images/oie_3QNUOMetbJh7.png" alt="Collab - Online Learning Platform">
                            </a>
                        </div>
                    </div>
                    <div class="col col-lg-6 col-2">
                        <nav class="main_menu navbar navbar-expand-lg">
                            <div class="main_menu_inner collapse navbar-collapse justify-content-center" id="main_menu_dropdown">
                                <ul class="main_menu_list unordered_list_center">
                                    <li><a class="nav-link" href="<?php echo  $this->url("home"); ?>">Home</a></li>
                                    <li><a class="nav-link" href="<?php echo $this->url("application", ["action" => "about"]) ?>">About Us</a></li>

                                    <li class="dropdown">
                                        <a class="nav-link" href="#" id="pages_submenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Programs
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="pages_submenu">
                                            <li><a href="about.html">Business Analysis Hands-On Program </a></li>

                                            <li><a href="faq.html">Business analysis Certification Program</a></li>

                                            <li><a href="pricing.html">Business Analysis On job Support</a></li>

                                        </ul>
                                    </li>
                                    <li><a class="nav-link" href="contact.html">Free Training</a></li>
                                    <li><a class="nav-link" href="<?= $this->url("application", ["action" => "about"]) . "#faq" ?>">FAQ</a></li>


                                    <li><a class="nav-link" href="contact.html">Contact</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                    <div class="col col-lg-3 col-5">
                        <ul class="header_btns_group unordered_list_end">
                            <li>
                                <button class="mobile_menu_btn" type="button" data-bs-toggle="collapse" data-bs-target="#main_menu_dropdown" aria-controls="main_menu_dropdown" aria-expanded="false" aria-label="Toggle navigation">
                                    <i class="far fa-bars"></i>
                                </button>
                            </li>
                            <li>
                                <a class="btn border_dark" href="">
                                    <span>
                                        <small>Login</small>
                                        <small>Login</small>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a class="btn btn_dark" href="">
                                    <span>
                                        <small>Sign Up</small>
                                        <small>Sign Up</small>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <!-- Site Header - End
================================================== -->

        <!-- Main Body - Start
================================================== -->
        <main class="page_content">
            <?= $this->content ?>
        </main>
        <!-- Main Body - End
================================================== -->

        <!-- Site Footer - Start
================================================== -->
        <footer class="site_footer">
            <div class="footer_widget_area">
                <div class="container">
                    <div class="row">
                        <div class="col col-lg-3 col-md-6 col-sm-6">
                            <div class="footer_widget">
                                <div class="site_logo">
                                    <a class="site_link" href="index.html">
                                        <img src="assets/images/logo/site_logo_2.svg" alt="Collab - Online Learning Platform">
                                    </a>
                                </div>
                                <p>
                                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
                                </p>
                                <ul class="social_links unordered_list">
                                    <li>
                                        <a href="#!"><i class="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="fab fa-youtube"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="fab fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#!"><i class="fab fa-linkedin-in"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col col-lg-6">
                            <div class="row">
                                <div class="col col-md-4 col-sm-4">
                                    <div class="footer_widget">
                                        <h3 class="footer_widget_title">Links</h3>
                                        <ul class="page_list unordered_list_block">
                                            <li>
                                                <a href="about.html">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">About</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="course.html">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Programs</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="mentor.html">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Free Training</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="pricing.html">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">FAQ</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="event.html">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Contact</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col col-md-4 col-sm-4">
                                    <div class="footer_widget">
                                        <h3 class="footer_widget_title">Program</h3>
                                        <ul class="page_list unordered_list_block">
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Business Analysis Hands-On Program</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Business analysis Certification Program</span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#!">
                                                    <span class="item_icon"><i class="fas fa-caret-right"></i></span>
                                                    <span class="item_text">Business Analysis On job Support</span>
                                                </a>
                                            </li>

                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="copyright_widget">
                <div class="container">
                    <p class="copyright_text text-center mb-0">
                        <a href="#"></a> © <b> Terces</b></b> All rights reserved Copyrights <?php date("Y") ?>
                    </p>
                </div>
            </div>
        </footer>
        <!-- Site Footer - End
================================================== -->

    </div>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/bootstrap-dropdown-ml-hack.js"></script>

    <!-- animation - jquery include -->
    <script src="/assets/js/cursor.js"></script>
    <script src="/assets/js/wow.min.js"></script>
    <script src="/assets/js/tilt.min.js"></script>
    <script src="/assets/js/parallax.min.js"></script>
    <script src="/assets/js/parallax-scroll.js"></script>

    <!-- Carousel - Jquery Include -->
    <script src="/assets/js/slick.min.js"></script>

    <!-- Video & Image Popup - Jquery Include -->
    <script src="/assets/js/magnific-popup.min.js"></script>

    <!-- Counter Up - Jquery Include -->
    <script src="/assets/js/waypoint.js"></script>
    <script src="/assets/js/counterup.min.js"></script>

    <!-- Countdown Timer - jquery include -->
    <script src="/assets/js/countdown.js"></script>

    <!-- Vanilla Calendar - Jquery Include -->
    <script src="/assets/js/vanilla-calendar.min.js"></script>

    <!-- Custom - Jquery Include -->
    <script src="/assets/js/main.js"></script>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>

</html>