<?php echo $this->headtitle("Edit Program"); ?>

<div id="editProgram">
    <input ref="programId" type="hidden" value="<?= $data->getId() ?>">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="tx-inverse mg-b-15"><?= $data->getTitle() ?></h3>
            <p class="mg-b-40"><?= $data->getDescription() ?></p>



        </div><!-- col-6 -->
        <div class="col-lg-6 mg-t-20 mg-sm-t-30 mg-lg-t-0">
            <div class="card card-dash-headline">


                <div class="row row-sm">
                    <div class="col-sm-6">
                        <a href="" class="btn btn-primary btn-block">Account Settings</a>
                    </div><!-- col-6 -->
                    <div class="col-sm-6 mg-t-10 mg-sm-t-0">
                        <a href="" class="btn btn-success btn-block">Upgrade Account</a>
                    </div><!-- col-6 -->
                </div><!-- row -->
            </div><!-- card -->
        </div><!-- col-6 -->
    </div><!-- row -->
    <hr>
    <div class="row row-xs mg-t-10">
        <div class="col-lg-6">
            <div class="card card-table">
                <div class="card-header">
                    <h6 class="slim-card-title">Program Courses</h6>
                </div><!-- card-header -->
                <div class="table-responsive">
                    <table class="table mg-b-0 tx-13">
                        <thead>
                            <tr class="tx-10">
                                <th>ID</th>
                                <th class="wd-10p pd-y-5">&nbsp;</th>
                                <th class="pd-y-5">Coure Details</th>
                                <th class="pd-y-10">Content</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($data->getCourses() as $key => $course) : ?>
                                <tr>
                                    <td><?= $course->getId() ?></td>
                                    <td class="pd-l-20">
                                        <img src="<?= $course->getBanner()->getImageUrl() ?>" class="wd-36 rounded-circle" alt="Image">
                                    </td>
                                    <td>
                                        <a href="" class="tx-inverse tx-14 tx-medium d-block"><?= $course->getTitle() ?></a>
                                        <span class="tx-11 d-block">UUID: <?= strtoupper($course->getUuid()) ?></span>
                                    </td>

                                    <td>
                                        <div class="row">
                                            <button @click="getCourseContent('<?= $course->getId() ?>')" class="btn btn-success btn-sm"><i class="fa fa-eye"></i></button>
                                            <button @click=" removeCourse('<?= $course->getId() ?>')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                            <button @click="editCourse('<?= $course->getId() ?>')" ref="editContentButton" data-toggle="modal" data-target="#modalEditCourse" class="btn btn-sm btn-warning"> <i class="fa fa-edit"></i>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach ?>

                        </tbody>
                    </table>
                </div><!-- table-responsive -->
                <div class="card-footer tx-12 pd-y-15 bg-transparent">
                    <button data-toggle="modal" data-target="#modalCreateCourse" class="btn btn-sm btn-warning"><i class="fa fa-angle-down mg-r-5"></i>Create Course</a>
                </div><!-- card-footer -->


                <!-- Begin Modal for create Course -->

                <div id="modalCreateCourse" class="modal fade">
                    <div class="modal-dialog modal-dialog-vertical-center" role="document">
                        <div class="modal-content bd-0 tx-14">
                            <div class="modal-header">
                                <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Message Preview</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body pd-25">
                                <div class="row">
                                    <div class="col-lg">
                                        <label>Course ID:</label>
                                        <input ref="courseId" class="form-control" placeholder="21" type="text">
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg">
                                        <label>Course Title:</label>
                                        <input ref="courseTitle" class="form-control" placeholder="Intro To businesss" type="text">
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <label>Course Description : </label>
                                        <textarea ref="courseDescription" class="form-control"></textarea>
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <div class="custom-file">
                                            <input type="file" ref="courseBanner" class="custom-file-input" id="customFile">
                                            <label class="custom-file-label" for="customFile">Upload Banner</label>
                                        </div><!-- custom-file -->
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <label>Video Link :</label>
                                        <input ref="courseVideo" class="form-control" placeholder="Intro To businesss" type="text">
                                    </div><!-- col -->
                                </div><!-- row -->
                            </div>
                            <div class="modal-footer">
                                <button @click="createCourse()" type="button" class="btn btn-primary">Create</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div><!-- modal-dialog -->
                </div><!-- modal -->

                <!-- End Modal for create Course -->


                <!-- Begin Modal for Edit Course -->

                <div id="modalEditCourse" class="modal fade">
                    <div class="modal-dialog modal-dialog-vertical-center" role="document">
                        <div class="modal-content bd-0 tx-14">
                            <div class="modal-header">
                                <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Edit Course</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body pd-25">

                                <div class="row">
                                    <div class="col-lg">
                                        <label>Edit ID:</label>
                                        <input ref="editCourseId" class="form-control" placeholder="Intro To businesss" type="text">
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg">
                                        <label>Edit Course Title:</label>
                                        <input ref="editCourseTitle" class="form-control" placeholder="Intro To businesss" type="text">
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <label>Edit Course Description : </label>
                                        <textarea class="form-control"></textarea>
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="customFile">
                                            <label class="custom-file-label" for="customFile">Upload Banner</label>
                                        </div><!-- custom-file -->
                                    </div><!-- col -->
                                </div>
                                <div class="row mg-t-20">
                                    <div class="col-lg mg-t-10 mg-lg-t-0">
                                        <label>Edit Video Link :</label>
                                        <input ref="editCourseVideo" class="form-control" placeholder="Intro To businesss" type="text">
                                    </div><!-- col -->
                                </div><!-- row -->
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary">Create</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div><!-- modal-dialog -->
                </div><!-- modal -->

                <!-- End Modal for create Course -->



            </div><!-- card -->
        </div><!-- col-6 -->
        <div v-if="!isFetchinContent" class="col-lg-6 mg-t-10 mg-lg-t-0">
            <div v-if="isCourseContent" class="card card-table">
                <div class="card-header">
                    <h6 class="slim-card-title">Course Content</h6>
                </div><!-- card-header -->
                <div class="table-responsive">
                    <table class="table mg-b-0 tx-13">
                        <thead>
                            <tr class="tx-10">
                                <th class="wd-10p pd-y-5">&nbsp;</th>
                                <th class="pd-y-5">Content Details</th>

                                <th class="pd-y-5">Video</th>
                                <th class="pd-y-5 tx-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr v-if="courseContent.length" v-for="cour in courseContent">
                                <td>{{cour.id}}</td>
                                <td>
                                    <a href="" class="tx-inverse tx-14 tx-medium d-block">{{cour.title}}</a>
                                    <span class="tx-11 d-block"><span class="square-8 bg-danger mg-r-5 rounded-circle"></span>
                                        {{cour.uuid.toUpperCase()}}</span>
                                </td>

                                <td class="pd-l-20">
                                    <a :href="cour.video" target="__blank"> <img :src="cour.banner.imageUrl" class="wd-55" alt="Image"></a>
                                </td>
                                <td class="valign-middle tx-center">
                                    <div class="row">
                                        <button @click="getCourseContent(cour.id)" class="btn btn-success btn-sm"><i class="fa fa-eye"></i></button>
                                        <button @click="removeCourseContent(cour.id)" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                        <button @click="editCourse(cour.id)" ref="editContentButton" data-toggle="modal" data-target="#modalEditCourse" class="btn btn-sm btn-warning"> <i class="fa fa-edit"></i>
                                        </button>
                                    </div>
                                </td>
                            </tr>



                        </tbody>
                    </table>
                </div><!-- table-responsive -->
                <div class="card-footer tx-12 pd-y-15 bg-transparent">
                    <button data-toggle="modal" data-target="#modalCreateContent" class="btn btn-sm btn-warning" href=""><i class="fa fa-plus-down mg-r-5"></i>Create Content</a>
                </div><!-- card-footer -->
            </div><!-- card -->
        </div><!-- col-6 -->
        <div v-else class="col-md-6 col-xl-6 mg-t-30">
            <div class="d-flex bg-200 ht-300 pos-relative align-items-center">
                <div class="sk-folding-cube">
                    <div class="sk-cube1 sk-cube"></div>
                    <div class="sk-cube2 sk-cube"></div>
                    <div class="sk-cube4 sk-cube"></div>
                    <div class="sk-cube3 sk-cube"></div>
                </div>
            </div><!-- d-flex -->
        </div><!-- col-4 -->

        <div id="modalCreateContent" class="modal fade">
            <div class="modal-dialog modal-dialog-vertical-center" role="document">
                <div class="modal-content bd-0 tx-14">
                    <div class="modal-header">
                        <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Create Content</h6>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body pd-25">
                        <div class="row">
                            <div class="col-lg">
                                <label>Content ID:</label>
                                <input ref="contentId" class="form-control" placeholder="21" type="text">
                            </div><!-- col -->
                        </div>
                        <div class="row mg-t-20">
                            <div class="col-lg">
                                <label>Content Title:</label>
                                <input ref="contentTitle" class="form-control" placeholder="Intro To businesss" type="text">
                            </div><!-- col -->
                        </div>
                        <div class="row mg-t-20">
                            <div class="col-lg mg-t-10 mg-lg-t-0">
                                <label>Content Description : </label>
                                <textarea ref="contentDescription" class="form-control"></textarea>
                            </div><!-- col -->
                        </div>
                        <div class="row mg-t-20">
                            <div class="col-lg mg-t-10 mg-lg-t-0">
                                <div class="custom-file">
                                    <input type="file" ref="contentBanner" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Upload Banner</label>
                                </div><!-- custom-file -->
                            </div><!-- col -->
                        </div>
                        <div class="row mg-t-20">
                            <div class="col-lg mg-t-10 mg-lg-t-0">
                                <label>Snippet Video Link :</label>
                                <input ref="contentVideoSnippet" class="form-control" placeholder="Intro To businesss" type="text">
                            </div><!-- col -->
                        </div><!-- row -->
                        <div class="row mg-t-20">
                            <div class="col-lg mg-t-10 mg-lg-t-0">
                                <label>Video Link :</label>
                                <input ref="contentVideo" class="form-control" placeholder="Intro To businesss" type="text">
                            </div><!-- col -->
                        </div><!-- row -->
                    </div>
                    <div class="modal-footer">
                        <button @click="createCourseContent()" type="button" class="btn btn-primary">Create</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div><!-- modal-dialog -->
        </div><!-- modal -->
    </div><!-- row -->

</div>
<script>
    const editProgram = Vue.createApp({
        data() {
            return {
                activeProgram: "",
                isCourseContent: false,
                isFetchinContent: false,
                courseContent: [],
                activeCourse: 0,
            }
        },


        methods: {

            createCourse() {
                this.isCreatingCourse = true;
                let fille = this.$refs.courseBanner.files[0];
                if (this.$refs.courseBanner.files.length == 0) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Empty Image',
                        text: "Image cannot be empty"
                    });
                } else if (this.$refs.courseId.value == "" ||
                    this.$refs.courseTitle.value == "" ||
                    this.$refs.courseDescription.value == "" ||
                    this.$refs.courseBanner.value == "" ||

                    this.$refs.courseVideo.value == "") {

                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'A required field is empty',

                    });
                } else if (fille > 1024 * 1024 * 2) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Image size',
                        text: "Image file should notbe more than 2MB",

                    });
                    this.isSubmitting = false;
                } else {
                    this.isCreatingCourse = false;


                    let formData = new FormData();
                    formData.append("id", this.$refs.courseId.value);
                    formData.append("title", this.$refs.courseTitle.value);
                    formData.append("description", this.$refs.courseDescription.value);
                    formData.append("banner", fille);
                    formData.append("video", this.$refs.courseVideo.value);
                    formData.append("program", this.$refs.programId.value);

                    axios.post("/admin/add-course", formData, {
                        headers: {
                            "Content-Type": "multipart/form-data"
                        }
                    }).then(res => {
                        if (res.status == 201) {
                            window.location.reload();
                        }
                    }).catch(err => {

                    });
                }
            },

            getCourseDetails(id) {

            },

            editCourse(id) {

            },

            removeCourse(id) {
                Swal.fire({
                    title: 'Are you sure you want to remove this course',
                    text: "This action is irreversible ",
                    showDenyButton: true,
                    showCancelButton: true,
                    confirmButtonText: 'Remove',
                    denyButtonText: `ignore`,
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        let formData = new FormData();
                        formData.append("key", id);
                        axios.post("/admin/remove-course", formData).then(res => {
                            if (res.status == 202) {
                                window.location.reload();
                            }
                        }).catch()
                    }
                })
            },

            getCourseContent(id) {
                // alert(id);
                this.isCourseContent = true;
                this.isFetchinContent = true;
                this.activeCourse = id;
                axios.get(`/admin/get-course-content/${id}`).then(res => {
                    if (res.status == 200) {
                        this.courseContent = res.data.data;
                        this.isFetchinContent = false;
                        this.isCourseContent = true;
                    }
                }).catch(err => {

                });
            },

            createCourseContent() {
                this.isCreatingCourse = true;
                let fille = this.$refs.contentBanner.files[0];
                if (this.$refs.contentBanner.files.length == 0) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Empty Image',
                        text: "Image cannot be empty"
                    });
                } else if (this.$refs.contentId.value == "" ||
                    this.$refs.contentTitle.value == "" ||
                    this.$refs.contentDescription.value == "" ||
                    this.$refs.contentBanner.value == "" ||

                    this.$refs.contentVideo.value == "") {

                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'A required field is empty',

                    });
                } else if (fille > 1024 * 1024 * 2) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Image size',
                        text: "Image file should notbe more than 2MB",

                    });
                    this.isSubmitting = false;
                } else {
                    this.isCreatingCourse = false;


                    let formData = new FormData();
                    formData.append("id", this.$refs.contentId.value);
                    formData.append("title", this.$refs.contentTitle.value);
                    formData.append("description", this.$refs.contentDescription.value);
                    formData.append("snippetVideo", "");
                    formData.append("banner", fille);
                    formData.append("video", this.$refs.contentVideo.value);
                    formData.append("course", this.activeCourse);

                    axios.post("/admin/add-course-content", formData, {
                        headers: {
                            "Content-Type": "multipart/form-data"
                        }
                    }).then(res => {
                        if (res.status == 201) {
                            window.location.reload();
                        }
                    }).catch(err => {

                    });
                }
            },

            editCourseContent() {

            },

            removeCourseContent(id) {
                Swal.fire({
                    title: 'Are you sure you want to remove this course',
                    text: "This action is irreversible ",
                    showDenyButton: true,
                    showCancelButton: true,
                    confirmButtonText: 'Remove',
                    denyButtonText: `ignore`,
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        let formData = new FormData();
                        formData.append("key", id);
                        axios.post("/admin/remove-course-content", formData).then(res => {
                            if (res.status == 202) {
                                window.location.reload();
                            }
                        }).catch()
                    }
                })

            }



        },
    });
    editProgramm = editProgram.mount("#editProgram");
    //https://www.youtube.com/embed/m-2PRSl8jQk
</script>