<?php echo $this->headtitle("Training List");
?>

<div class="section-wrapper mg-t-20">
    <label class="section-title">Sudcribed Users</label>
    <p class="mg-b-20 mg-sm-b-40">Users and and programs they subscibe to</p>

    <div class="table-responsive">
        <table class="table table-bordered table-colored table-primary">
            <thead>
                <tr>
                    <th class="wd-10p">ID</th>
                    <th class="wd-35p">Title</th>
                    <th class="wd-35p">Active</th>
                    <th class="wd-20p"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $da) : ?>
                <tr>
                    <th scope="row"><?= $da["id"] ?></th>
                    <td><?= $da["title"] ?></td>
                    <td><?= $da["isActive"]?></td>
                    <td><a href="<?= $this->url("admin", ["action" => "course-list", "id" => $da["uuid"]]) ?>"><i
                                class="icon ion-eye tx-20"></i></a> | <a
                            href="<?= $this->url("admin", ["action" => "edit-program", "id" => $da["uuid"]]) ?>"><i
                                class="icon ion-edit tx-20"></i></a>
                    </td>
                </tr>
                <?php endforeach ?>

            </tbody>
        </table>
    </div><!-- table-responsive -->

</div><!-- section-wrapper -->