<?php echo $this->headtitle("Search for user"); ?>


<div id="interac" class="section-wrapper mg-t-20">
    <label class="section-title">Sudcribed Users</label>
    <p class="mg-b-20 mg-sm-b-40">Users and and programs they subscibe to</p>

    <form method="POST">
        <div class="d-sm-flex wd-sm-600">
            <div class="form-group mg-b-0">
                <label>Search for user: <span class="tx-danger">*</span></label>
                <input type="text" name="keyword" class="form-control wd-150 wd-xs-250" placeholder="Enter Email or name" required>
            </div><!-- form-group -->
            <div class="mg-sm-l-10 mg-t-10 mg-sm-t-25 pd-t-4">
                <input type="submit" class="btn btn-primary pd-x-20" value="Search User">
            </div>
        </div>
    </form>
    <hr>
    <div class="table-responsive">
        <?php if ($data != NULL): ?>
            <table class="table table-bordered table-colored table-purple">
                <thead>

                    <tr>
                        <th class="wd-10p">ID</th>
                        <th class="wd-35p">Name</th>
                        <th class="wd-35p">Role</th>

                        <th class="wd-10p">Action</th>
                    </tr>

                </thead>
                <tbody>
                    <?php

                    foreach ($data as $key => $da) : ?>
                        <tr>
                            <th scope="row"><?= $da["id"] ?></th>
                            <td><strong>Fullname : </strong><?= $da["fullname"] ?> <br>
                                <strong>Email : </strong> <?= $da["email"] ?>


                            </td>
                            <td><?= $da["role"]["name"] ?></td>

                            </td>
                            <td>
                                <div class="row">
                                    <button class="btn btn-sm btn-primary" @click="activeUser(<?= $da['id'] ?>)" href="#modaldemo1" data-toggle="modal" data-effect="effect-scale"><i class="fa fa-eye"></i></button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach;

                    ?>

                    <div id="modaldemo1" class="modal fade">
                        <div class="modal-dialog modal-dialog-vertical-center" role="document">
                            <div class="modal-content bd-0 tx-14">
                                <div class="modal-header">
                                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Create a Training</h6>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body pd-25">
                                    <div class="alert alert-outline alert-warning" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <strong>TIMEZONE</strong> All timezone are registered as UTC
                                    </div><!-- alert -->
                                    <div class="row">
                                        <label for="eventTime">Select Event Time</label>
                                        <input v-model="formSelectedEventDatetime" class="form-control" type="datetime-local" id="eventTime" name="eventTime">
                                    </div>
                                    <br>

                                    <div class="row">
                                        <label for="eventDuration">Cohort</label>
                                        <select v-model="selectedCohort" class="form-control">
                                            <option v-for="ch in cohort" value="ch.id">{{ch.cohortName}}</option>

                                        </select>
                                    </div>

                                    <div class="row">

                                    </div>

                                    <!--   <h5 class="lh-3 mg-b-20"><a href="" class="tx-inverse hover-primary">Why We Use Electoral College, Not Popular Vote</a></h5>
                                        <p class="mg-b-5">It is a long established fact that a 
                                            reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here',
                                             making it look like readable English. </p> -->
                                </div>
                                <div class="modal-footer">
                                    <div v-if="isCreatingEvent" class="d-flex bg-gray-200 ht-20 pos-relative align-items-center">
                                        <div class="sk-folding-cube">
                                            <div class="sk-cube1 sk-cube"></div>
                                            <div class="sk-cube2 sk-cube"></div>
                                            <div class="sk-cube4 sk-cube"></div>
                                            <div class="sk-cube3 sk-cube"></div>
                                        </div>
                                    </div><!-- d-flex -->
                                    <button v-else @click="createEventMeeting()" type="button" class="btn btn-primary">Create Event</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div><!-- modal-dialog -->
                    </div><!-- modal -->
                </tbody>
            </table>
        <?php endif; ?>
    </div><!-- table-responsive -->

</div><!-- section-wrapper -->

<script>
    const app = Vue.createApp({
        data() {
            return {
                data: [],
                cohort: [],
                selectedUser: "",
                selectedCohort: "",
            }
        },
        mounted() {
            this.getCohort();
        },

        methods: {

            getCohort() {
                axios.get("/admins/oracle/get-cohort").then((result) => {
                    if (result.status == 200) {
                        // console.log(result.data.data);
                        this.cohort = result.data.data;
                    }
                }).catch((err) => {

                });
            },
            activeUser(id) {
                this.selectedUser = id;
            },
            assignToCohort(data) {
                if (this.activeUser == "" || this.selectedCohort == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Error",
                        text: "Required varibale absent",
                    });
                } else {
                    let formData = new FormData();
                    formData.append("user", this.activeUser);
                    formData.append("cohort", this.selectedCohort);
                    axios.post("", formData).then((result) => {

                    }).catch((err) => {

                    });
                }
            }
        },
    });
    app.mount("#interac");
</script>