<?php $this->headtitle("Registedred"); ?>


<div class="section-wrapper mg-t-20">
    <label class="section-title">Sudcribed Users</label>
    <p class="mg-b-20 mg-sm-b-40">Users and and programs they subscibe to</p>

    <div class="table-responsive">
        <table class="table table-bordered table-colored table-purple">
            <thead>

                <tr>
                    <th class="wd-10p">ID</th>
                    <th class="wd-35p">Name</th>

                    <th class="wd-20p">Registered On</th>
                    <th class="wd-10p">Action</th>
                </tr>

            </thead>
            <tbody>
                <?php foreach ($data as $key => $da) : ?>
                    <tr>
                        <th scope="row"><?= $da["id"] ?></th>
                        <td><strong>Fullname : </strong><?= $da["user"]["fullname"] ?> <br>
                            <strong>Email : </strong> <?= $da["user"]["email"] ?>


                        </td>

                        <td><?= $this->dateformat($da["user"]["registrationDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?>
                        </td>
                        <td>
                            <div class="row">
                                <a href="<?= $this->url("admin-general", ["controller" => "oracle", "action" => "view", "id" => $da["uuid"]]) ?>" class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div><!-- table-responsive -->

</div><!-- section-wrapper -->