<?= $this->headtitle("View user"); ?>

<?php //var_dump($data); 
?>
<div id="p6View" class="row row-sm">
    <div class="col-lg-8">
        <div class="card card-profile">
            <div class="card-body">
                <div class="media">
                    <img src="<?= $data["program"]["banner"] ?>" alt="">
                    <div class="media-body">
                        <h3 class="card-profile-name"><?= $data["user"]["fullname"] ?></h3>
                        <p class="card-profile-position">Program: <a><?= $data["program"]["title"] ?></a></p>
                        <p><?= $data["status"]["status"] ?></p>

                        <!--  <p class="mg-b-0">A consummate human capital management professional with international training and talent management implementations experience across the entire universe...<a href="">Read more</a></p> -->
                    </div><!-- media-body -->
                </div><!-- media -->
            </div><!-- card-body -->
            <div class="card-footer">
                <!--    <a href="" class="card-profile-direct">http://thmpxls.me/profile?id=katherine</a> -->
                <div>
                    <a href="">Edit Profile</a>
                    <a href="">Profile Settings</a>
                </div>
            </div><!-- card-footer -->
        </div><!-- card -->

        <ul class="nav nav-activity-profile mg-t-20">
            <li class="nav-item"><a href="" class="nav-link"><i class="icon ion-ios-redo tx-purple"></i> Share an update</a></li>
            <li class="nav-item"><a href="" class="nav-link"><i class="icon ion-image tx-primary"></i> Publish photo</a></li>
            <li class="nav-item"><a href="" class="nav-link"><i class="icon ion-document-text tx-success"></i> Add an article</a></li>
        </ul><!-- nav -->


        <div class="card card-experience mg-t-20">
            <?php if ($data["oracleCohort"] == NULL) : ?>
                <div class="card-body">
                    <div class="slim-card-title">Assigned Cohort</div>
                    <hr>
                    <button href="#modaldemo8" data-toggle="modal" data-effect="effect-scale" class="modal-effect btn btn-primary btn-block mg-b-10">Assign To Cohort</button>
                </div>



                <div id="modaldemo8" class="modal fade">
                    <div class="modal-dialog modal-dialog-vertical-center" role="document">
                        <div class="modal-content bd-0 tx-14">
                            <div class="modal-header pd-y-20 pd-x-25">
                                <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Assign User To Cohort</h6>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body pd-25">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="input-group">

                                            <select v-if="cohort.length" v-model="assignCohort" class="form-control">
                                                <option v-for="co in cohort" :value="co.id">{{co.cohort}} (<strong>{{formatPHPDate(co.startDate.date).toDateString()}}</strong>)</option>
                                            </select>
                                        </div><!-- input-group -->
                                    </div><!-- col-4 -->

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button @click="assignToCohort()" type="button" class="btn btn-primary">Assign</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div><!-- modal-dialog -->
                </div><!-- modal -->



            <?php else : ?>
                <div class="card-body">
                    <div class="slim-card-title">Assigned Cohort</div>
                    <div class="media">
                        <div class="experience-logo">
                            <i class="icon ion-briefcase"></i>
                        </div><!-- experience-logo -->
                        <div class="media-body">
                            <h6 class="position-name"><?= strtoupper($data["oracleCohort"]["p6Cohort"]["cohort"]) ?></h6>
                            <!-- <p class="position-company">Cebu Machine Intelligence, Inc.</p>-->
                            <p class="position-year"><strong>START DATE: </strong><?= $this->dateFormat($data["oracleCohort"]["p6Cohort"]["startDate"], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?> </p>
                        </div><!-- media-body -->
                    </div><!-- media -->
                </div><!-- card-body -->
                <div class="card-footer">
                    <!-- <a href="">Show more<span class="d-none d-sm-inline"> experiences (4)</span> <i class="fa fa-angle-down"></i></a> -->
                    <a href="">REASSIGN</a>
                </div><!-- card-footer -->

            <?php endif; ?>

        </div><!-- card -->


    </div><!-- col-8 -->

    <div class="col-lg-4 mg-t-20 mg-lg-t-0">
        



        <div class="card pd-25 mg-t-20">
            <div class="slim-card-title">User &amp; Info</div>

            <div class="media-list mg-t-25">
                <div class="media">
                    <div><i class="icon ion-link tx-24 lh-0"></i></div>
                    <div class="media-body mg-l-15 mg-t-4">
                        <h6 class="tx-14 tx-gray-700">Websites</h6>
                        <a href="" class="d-block">http://themepixels.me</a>
                        <a href="" class="d-block">http://themeforest.net</a>
                    </div><!-- media-body -->
                </div><!-- media -->
                <div class="media mg-t-25">
                    <div><i class="icon ion-ios-telephone-outline tx-24 lh-0"></i></div>
                    <div class="media-body mg-l-15 mg-t-4">
                        <h6 class="tx-14 tx-gray-700">Full Name</h6>
                        <span class="d-block"><?= $data["user"]["fullname"] ?></span>
                    </div><!-- media-body -->
                </div><!-- media -->
                <div class="media mg-t-25">
                    <div><i class="icon ion-ios-email-outline tx-24 lh-0"></i></div>
                    <div class="media-body mg-l-15 mg-t-4">
                        <h6 class="tx-14 tx-gray-700">Email Address</h6>
                        <span class="d-block">yourname@sample.com</span>
                    </div><!-- media-body -->
                </div><!-- media -->
                <div class="media mg-t-25">
                    <div><i class="icon ion-social-twitter tx-18 lh-0"></i></div>
                    <div class="media-body mg-l-15 mg-t-2">
                        <h6 class="tx-14 tx-gray-700">Twitter</h6>
                        <a href="#" class="d-block">@themepixels</a>
                    </div><!-- media-body -->
                </div><!-- media -->
            </div><!-- media-list -->
        </div><!-- card -->
    </div><!-- col-4 -->
</div><!-- row -->

<script>
    const p6View = Vue.createApp({
        data() {
            return {
                cohort: [],
                assignCohort: "",
                activeUserProgram: '<?= $data["id"] ?>',
            }
        },
        mounted() {
            this.getCohort();
        },
        methods: {
            formatPHPDate(date) {
                // myDate = date.replace(/-/g, "/");
                return new Date(date);

            },
            getCohort() {
                axios.get("/admins/oracle/get-cohort").then((result) => {
                    if (result.status == 200) {
                        // console.log(result.data.data);
                        this.cohort = result.data.data;
                    }
                }).catch((err) => {

                });
            },
            assignToCohort() {
                // alert("KKKK");
                if (this.assignToCohort == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Required Field",
                        text: "A required field is empty"
                    });
                } else {
                    let formData = new FormData();
                    formData.append("cohort", this.assignCohort);
                    formData.append("activeUserProgram", this.activeUserProgram);

                    axios.post("/admins/oracle/assign-to-cohort", formData).then((result) => {
                        if (result.status == 201) {
                            window.location.reload();
                        }
                    }).catch((err) => {

                    });
                }
            },
        },
    });
    p6View.mount("#p6View");
</script>