<div class="card card-table">
    <div class="card-header">
        <h6 class="slim-card-title">Registered User</h6>
    </div><!-- card-header -->
    <div class="table-responsive">
        <table class="table mg-b-0 tx-13">
            <thead>
                <tr class="tx-10">

                    <th class="pd-y-5">User Details</th>
                    <th class="pd-y-5 tx-right">Program</th>
                    <th class="pd-y-5 tx-right">Status</th>
                    <th class="pd-y-5 tx-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr v-if="registeredUser.length" v-for="user in registeredUser">

                    <td>
                        <a href="" class="tx-inverse tx-14 tx-medium d-block">{{user.user.fullname}}</a>
                        <span class="tx-15 d-block"></span> {{user.user.email}}</span>
                    </td>
                    <td class="valign-middle tx-right">{{user.program.title}}</td>
                    <td class="valign-middle tx-right">{{user.status.status}}</td>
                    <td class="valign-middle tx-center">
                        <div v-if="isAssigning">
                            <div class="sk-folding-cube">
                                <div class="sk-cube1 sk-cube"></div>
                                <div class="sk-cube2 sk-cube"></div>
                                <div class="sk-cube4 sk-cube"></div>
                                <div class="sk-cube3 sk-cube"></div>
                            </div>
                        </div>
                        <div v-else>
                            <a v-if="user.user.state.id != 2" @click="assign(user.id)" title="Assign to Cohort" class="tx-gray-600 tx-24"><i class="fa fa-xs fa-wrench"></i></a>

                        </div>


                    </td>
                </tr>

            </tbody>
        </table>
    </div><!-- table-responsive -->
    <div class="card-footer tx-12 pd-y-15 bg-transparent">
        <a href="<?= $this->url("admin", ["action" => "user-list"]) ?>"><i class="fa fa-angle-down mg-r-5"></i>View All Users</a>
    </div><!-- card-footer -->
</div><!-- card -->