<?php $this->headtitle("Course"); ?>


<div id="course" class="page-section">
    <div class="row">

        <div class="col-md-9">

            <?php foreach ($data as $dat) : ?>
                <div class="panel panel-default paper-shadow" data-z="0.5">
                    <div class="panel-body">

                        <div class="media media-clearfix-xs">
                            <div class="media-left text-center">
                                <div class="cover width-150 width-100pc-xs overlay cover-image-full hover margin-v-0-10">
                                    <span class="img icon-block height-130 bg-default"></span>
                                    <span class="overlay overlay-full padding-none icon-block bg-default">
                                        <span class="v-center">
                                            <img src="<?= $dat->getProgram()->getBanner(); ?>" class="img-circle width-100">
                                        </span>
                                    </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                        <span class="v-center">
                                            <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                        </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="text-headline margin-v-5-0"><a href="<?= $this->url("internship", ["controller" => "courses", "action" => "info", "id" => $dat->getProgram()->getUuid()]) ?>"><?= $dat->getProgram()->getTitle() ?></h4>


                            </div>
                        </div>

                    </div>
                </div>
            <?php endforeach; ?>


            <br />

        </div>
        <div class="col-md-3">
            <?= $this->partial("partial/my-course-menu"); ?>

        </div>

    </div>
</div>

<script>
    const courseApp = Vue.createApp({
        data() {
            return {
                registeredCourses: [],

            }
        },
        methods: {
            getCourses() {
                axios.get().then((result) => {

                }).catch((err) => {

                });
            }
        },
    });
    courseApp.mount("#course");
</script>