<div class="page-section">
    <div class="row">

        <div class="col-md-9">

            <div class="row" data-toggle="isotope">
                <?php if (!$isAssigned) : ?>

                    <div class="panel panel-default">
                        <div class="media v-middle">
                            <div class="media-left">
                                <div class="bg-orange-400 text-white">
                                    <div class="panel-body">
                                        <i class="fa fa-warning fa-fw fa-2x"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="media-body">
                                You have not been assigned to a cohort for this course
                            </div>
                            <div class="media-right media-padding">
                                <a class="btn btn-white paper-shadow relative" data-z="0.5" data-hover-z="1" data-animated href="#">
                                    Make Request
                                </a>
                            </div>
                        </div>
                    </div>

                <?php else :  ?>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 4 of 12
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-grey-600" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-default"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-default">
                                    <span class="v-center">

                                        <i class="fa fa-video-camera"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">Github Webhooks for Beginners</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 2 of 13
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-blue-300" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-primary"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-primary">
                                    <span class="v-center">
                                        <i class="fa fa-css3"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-primary btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">Awesome CSS with LESS Processing</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 2 of 6
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-red-300" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-lightred"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-lightred">
                                    <span class="v-center">
                                        <i class="fa fa-windows"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-red-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">Vagrant Portable Environments</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 3 of 18
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-orange-300" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-brown"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-brown">
                                    <span class="v-center">
                                        <i class="fa fa-wordpress"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-orange-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">WordPress Theme Development</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 2 of 13
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-deep-purple-300" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-purple"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-purple">
                                    <span class="v-center">
                                        <i class="fa fa-jsfiddle"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-purple-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">Browserify: Writing Modular JavaScript</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>
                    <div class="item col-xs-12 col-sm-6 col-lg-4">
                        <div class="panel panel-default paper-shadow" data-z="0.5">

                            <div class="panel-heading">
                                <div class="media media-clearfix-xs-min v-middle">
                                    <div class="media-body text-caption text-light">
                                        Lessons 2 of 18
                                    </div>
                                    <div class="media-right">
                                        <div class="progress progress-mini width-100 margin-none">
                                            <div class="progress-bar progress-bar-pink-300" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="cover overlay cover-image-full hover">
                                <span class="img icon-block height-100 bg-pink-400 text-white"></span>
                                <a href="website-take-course.html" class="padding-none overlay overlay-full icon-block bg-pink-400 text-white">
                                    <span class="v-center">
                                        <i class="fa fa-cc-visa"></i>
                                    </span>
                                </a>

                                <a href="website-take-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                    <span class="v-center">
                                        <span class="btn btn-circle btn-pink-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                    </span>
                                </a>

                            </div>

                            <div class="panel-body">
                                <h4 class="text-headline margin-v-0-10"><a href="website-take-course.html">Online Payments with Stripe</a></h4>

                            </div>
                            <hr class="margin-none" />
                            <div class="panel-body">

                                <a class="btn btn-white btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated href="website-take-course.html">Go to course</a>

                            </div>

                        </div>
                    </div>

                <?php endif; ?>
            </div>



            <br />
            <br />

        </div>
        <div class="col-md-3">



            <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                <div class="panel-heading">
                    <h4 class="text-headline">Course</h4>
                </div>
                <div class="panel-body">
                    <p class="text-caption">
                        <i class="fa fa-clock-o fa-fw"></i> <?= $course->getDuration() ?> &nbsp;
                        <i class="fa fa-calendar fa-fw"></i>
                        <br />
                        <i class="fa fa-user fa-fw"></i> Instructor: <?= $course->getInstructor() ?>
                        <br />
                        <i class="fa fa-mortar-board fa-fw"></i> Course. <?= $course->getTitle() ?>
                        <br />
                        <!--  <i class="fa fa-check fa-fw"></i> Attending: 30 -->
                    </p>
                </div>
                <hr class="margin-none" />

                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="#" class="text-light"><i class="fa fa-eye fa-fw"></i> View receipt</a>
                    </li>

                </ul>
            </div>



            <?= $this->partial("partial/course-info-menu", ["title" => $course->getTitle()]) ?>



        </div>

    </div>
</div>