<div id="infoApp" class="page-section">
    <div class="row">

        <div class="col-md-9">

            <div class="row" data-toggle="isotope">

                <div v-if="zoomClasses.length" v-for="cla in zoomClasses" class="item col-xs-12 col-sm-6 col-lg-4">
                    <div class="panel panel-default paper-shadow" data-z="0.5">

                        <div class="panel-heading">
                            <div class="media media-clearfix-xs-min v-middle">
                                <div class="media-body text-caption text-light">
                                    START: {{readableDate(cla.zoomStartTime)}} UTC
                                </div>

                            </div>
                        </div>

                        <div class="cover overlay cover-image-full hover">
                            <span class="img icon-block height-100 bg-default"></span>
                            <a href="" class="padding-none overlay overlay-full icon-block bg-default">
                                <span class="v-center">

                                    <i class="fa fa-video-camera"></i>
                                </span>
                            </a>

                            <a target="_blank" :href="cla.zoomJoinUrl" class="overlay overlay-full overlay-hover overlay-bg-white">
                                <span class="v-center">
                                    <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-video"></i></span>
                                </span>
                            </a>

                        </div>

                        <div class="panel-body">
                            <h4 class="text-headline margin-v-0-10"><a href="">{{cla.program.title}}</a></h4>

                        </div>
                        <hr class="margin-none" />
                        <div class="panel-body">
                            <a class="btn btn-primary btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated target="_blank" :href="">View Details</a>
                            <a class="btn btn-info btn-flat paper-shadow relative" data-z="0" data-hover-z="1" data-animated target="_blank" :href="cla.zoomJoinUrl">Go to Zoom Class</a>
                        </div>

                    </div>
                </div>

            </div>



            <br />
            <br />

        </div>
        <div class="col-md-3">



            <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                <div class="panel-heading">
                    <h4 class="text-headline">Course</h4>
                </div>
                <div class="panel-body">
                    <p class="text-caption">
                        <i class="fa fa-clock-o fa-fw"></i> <?= $course->getDuration() ?> &nbsp;
                        <i class="fa fa-calendar fa-fw"></i>
                        <br />
                        <i class="fa fa-user fa-fw"></i> Instructor: <?= $course->getInstructor() ?>
                        <br />
                        <i class="fa fa-mortar-board fa-fw"></i> Course. <?= $course->getTitle() ?>
                        <br />
                        <!--  <i class="fa fa-check fa-fw"></i> Attending: 30 -->
                    </p>
                </div>
                <hr class="margin-none" />

                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="#" class="text-light"><i class="fa fa-eye fa-fw"></i> View receipt</a>
                    </li>

                </ul>
            </div>



            <?= $this->partial("partial/course-info-menu", ["title" => $course->getTitle()]) ?>



        </div>

    </div>
</div>

<script>
    const classInfoApp = Vue.createApp({
        data() {
            return {
                zoomClasses: [],
                program: '<?= $course->getId(); ?>'
            }
        },
        mounted() {
            this.getZoomClasses();
        },
        methods: {
            getZoomClasses() {
                axios.get("/internships/courses/get-zoom-clases", {
                    params: {
                        program: this.program
                    }
                }).then((result) => {
                    if (result.status == 200) {
                        this.zoomClasses = result.data.data;
                    }

                }).catch((err) => {

                });
            },
            readableDate(da) {
                var d = new Date(da);
                return d.toDateString();
            }
        },


    });
    classInfoApp.mount("#infoApp");
</script>