    <!-- Page Section - Start
        ================================================== -->
    <section class="page_banner">
        <div class="container">
            <div class="content_wrapper" style="background-image: url('/assets/images/1.png');">
                <div class="row align-items-center">
                    <div class="col col-lg-6">
                        <ul class="breadcrumb_nav unordered_list">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="#!">Pages</a></li>
                            <li>About Us</li>
                        </ul>
                        <h1 class="page_title">About Terces Academy</h1>
                        <p class="page_description">
                            Terces Academy helps non-tech individual nagigate through the tech space, and smoothly pivot into the tech industry through business Analysis
                        </p>
                        <!-- <form action="#">
                            <div class="form_item mb-0">
                                <input type="search" name="search" placeholder="What do you want to learn ?">
                                <button type="submit" class="btn btn_dark">
                                    <span>
                                        <small>Search</small>
                                        <small>Search</small>
                                    </span>
                                </button>
                            </div>
                        </form>-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Page Section - End
        ================================================== -->

    <!-- Courses Info Section - Start
        ================================================== -->
    <section class="courses_info_section section_space_lg pb-0">
        <div class="container">
            <div class="row align-items-center">
                <div class="col col-lg-6">
                    <div class="image_widget">
                        <img src="assets/images/4.png" alt="Terces – Online Learning Platform">
                    </div>
                </div>
                <div class="col col-lg-6">
                    <div class="content_wrap ps-lg-3">
                        <div class="section_heading">
                            <h2 class="heading_text">
                                Available Programs
                            </h2>
                            <!--  <p class="heading_description mb-0">
                                Rutrum tellus pellentesque eu tincidunt. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Sit amet porttitor eget dolor morbi
                            </p> -->
                        </div>
                        <ul class="info_list unordered_list_block">
                            <li>
                                <i class="fas fa-square"></i>
                                <span>
                                    Business Analysis Masterclass (free)
                                </span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>
                                    Business Analysis Hands-On Program (Paid)
                                </span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>
                                    Business analysis Certification Program (Paid)
                                </span>
                            </li>

                            <li>
                                <i class="fas fa-square"></i>
                                <span>
                                    Business Analysis On job Support (Paid)
                                </span>
                            </li>
                        </ul>
                        <div class="btn_wrap pb-0">
                           <!-- <a class="btn btn_dark" href="mentor.html">
                                <span>
                                    <small>Our Mentors</small>
                                    <small>Our Mentors</small>
                                </span> -->
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Courses Info Section - End
        ================================================== -->

    <!-- Policy Section - Start
        ================================================== -->
    <section class="policy_section section_space_lg">
        <div class="container position-relative">
            <div class="section_heading">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col col-lg-6">
                        <h2 class="heading_text mb-lg-0">
                            What we offer
                        </h2>
                    </div>
                    <div class="col col-lg-4">
                        <p class="heading_description mb-0 text-lg-end">
                           <!-- Lobortis mattis aliquam faucibus purus in. Ultricies integer quis auctor elit sed -->
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col col-lg-3 col-md-6">
                    <div class="iconbox_item">
                        <div class="title_wrap">
                            <div class="item_icon bg_dark">
                                <i class="fas fa-book-open"></i>
                            </div>
                            <h3 class="item_title mb-0">
                                <span class="d-block"> Business Analysis Masterclass </span>
                                <div style="color: red;">(free)</div>
                            </h3>
                        </div>
                        <p class="mb-0">
                            This is a quick and fastrack program, designed to get you started into the world of business Analysis
                        </p>
                    </div>
                </div>
                <div class="col col-lg-3 col-md-6">
                    <div class="iconbox_item">
                        <div class="title_wrap">
                            <div class="item_icon bg_dark">
                                <i class="fas fa-code-branch"></i>
                            </div>
                            <h3 class="item_title mb-0">
                                <span class="d-block">Business Analysis Hands-On Program </span>
                                <div style="color: green;"> (Paid)</div>
                            </h3>
                        </div>
                        <p class="mb-0">
                            you would learn how to gather business requirements from various methodologies i.e agile and waterfall.(user stories and traditional BRD)
                        </p>
                    </div>
                </div>
                <div class="col col-lg-3 col-md-6">
                    <div class="iconbox_item">
                        <div class="title_wrap">
                            <div class="item_icon bg_dark">
                                <i class="fas fa-comment-smile"></i>
                            </div>
                            <h3 class="item_title mb-0">
                                <span class="d-block">Business analysis Certification Program </span>
                                <div style="color: green;"> (Paid)</div>
                            </h3>
                        </div>
                        <p class="mb-0">
                            Here you would learn about the various Business analysis techniques and the 6 Knowledge areas and IIBA simulation tests
                        </p>
                    </div>
                </div>
                <div class="col col-lg-3 col-md-6">
                    <div class="iconbox_item">
                        <div class="title_wrap">
                            <div class="item_icon bg_dark">
                                <i class="fas fa-user-graduate"></i>
                            </div>
                            <h3 class="item_title mb-0">
                                <span class="d-block">Business Analysis On job Support </span>
                                <div style="color: green;">(Paid)</div>
                            </h3>
                        </div>
                        <p class="mb-0">
                            We provide you with tools, tricks and knowledge to close that employment interview and subsequently excel at your work
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Policy Section - End
        ================================================== -->


    <!-- Popular Event Section - Start
        ================================================== -->
    <section class="popular_event_section section_space_lg bg_dark decoration_wrap">
        <div class="container">
            <div class="row align-items-center">
                <div class="col col-lg-7">
                    <div class="section_heading mb-lg-0">
                        <h2 class="heading_text text-white">
                            Our upcoming events
                        </h2>
                        <p class="heading_description mb-0 text-white">
                            <!--  Rhoncus dolor purus non enim praesent elementum facilisis. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Iaculis eu non diam phasellus vestibulum lorem sed risus. -->
                        </p>
                        <div class="btn_wrap pb-0">
                            <a class="btn btn_primary" href="event.html">
                                <span>
                                    <small>All Events</small>
                                    <small>All Events</small>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col col-lg-5">
                    <div class="popular_event_list">
                        <h3 class="wrap_title">Upcoming Events</h3>
                        <ul class="unordered_list_block">
                            <li>
                                <div class="column">
                                    <b class="day">12</b>
                                    <span class="month">february</span>
                                    <strong class="time">03:50 PM</strong>
                                </div>
                                <div class="column">
                                    <h4 class="event_title">Digital Transformation Conference</h4>
                                    <span class="event_name">
                                        <strong>Prepare for:</strong> <small>Lora Hill</small>
                                    </span>
                                </div>
                            </li>
                            <li>
                                <div class="column">
                                    <b class="day">12</b>
                                    <span class="month">february</span>
                                    <strong class="time">03:50 PM</strong>
                                </div>
                                <div class="column">
                                    <h4 class="event_title">Digital Transformation Conference</h4>
                                    <span class="event_name">
                                        <strong>Prepare for:</strong> <small>Lora Hill</small>
                                    </span>
                                </div>
                            </li>
                            <li>
                                <div class="column">
                                    <b class="day">12</b>
                                    <span class="month">february</span>
                                    <strong class="time">03:50 PM</strong>
                                </div>
                                <div class="column">
                                    <h4 class="event_title">Digital Transformation Conference</h4>
                                    <span class="event_name">
                                        <strong>Prepare for:</strong> <small>Lora Hill</small>
                                    </span>
                                </div>
                            </li>
                            <li>
                                <div class="column">
                                    <b class="day">12</b>
                                    <span class="month">february</span>
                                    <strong class="time">03:50 PM</strong>
                                </div>
                                <div class="column">
                                    <h4 class="event_title">Digital Transformation Conference</h4>
                                    <span class="event_name">
                                        <strong>Prepare for:</strong> <small>Lora Hill</small>
                                    </span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="deco_item shape_img_1" data-parallax='{"y" : 130, "smoothness": 6}'>
            <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
        </div>
        <div class="deco_item shape_img_2" data-parallax='{"x" : -130, "smoothness": 6}'>
            <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
        </div>
        <div class="deco_item shape_img_3" data-parallax='{"y" : -130, "smoothness": 6}'>
            <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
        </div>
    </section>
    <!-- Popular Event Section - End
        ================================================== -->

    <!-- FAQ Section - Start
        ================================================== -->
    <?= $this->partial("partials_faq"); ?>
    <!-- FAQ Section - End
        ================================================== -->

    <?= $this->partial("partials_newsletter"); ?>