<!-- Page Section - Start
        ================================================== -->
<section class="page_banner">
  <div class="container">
    <div class="content_wrapper">
      <div class="row align-items-center">
        <div class="col col-lg-7">
          <ul class="breadcrumb_nav unordered_list">
            <li><a href="index.html">Home</a></li>
            <li><a href="course.html">Course</a></li>
            <li>Business Analysis Masterclass</li>
          </ul>
          <h1 class="page_title">
            Begin Your Business Analysis Journey
          </h1>
          <ul class="meta_info_list unordered_list">
            <li>
              <i class="fas fa-chart-bar"></i>
              <span>Beginner</span>
            </li>
            <li>
              <i class="fas fa-clock"></i>
              <span>2 Hours</span>
            </li>
            <!--<li>
                      <i class="fas fa-star"></i>
                      <span>3.5 (3k reviews)</span>
                    </li>-->
          </ul>
          <ul class="btns_group unordered_list">
            <li>
              <div class="item_price">
                <del class="remove_price">Free</del>
                <span class="sale_price">Free</span>
              </div>
            </li>
            <li>
              <a href="pricing.html" class="btn btn_dark">
                <span>
                  <small>Register Now</small>
                  <small>Register Now</small>
                </span>
              </a>
            </li>
          </ul>
        </div>
        <div class="col col-lg-5">
          <div class="image_widget page_banner_image">
            <img src="assets/images/banner/page_banner_image_1.jpg" alt="Terces – Online Learning Platform">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page Section - End
        ================================================== -->

<!-- Courses Info Section - Start
        ================================================== -->
<section class="details_section courses_info_section section_space_lg">
  <div class="container">
    <div class="row">
      <div class="col col-lg-6">
        <div class="content_wrap">
          <div class="section_heading">
            <h2 class="heading_text mb-0">
              What You will Learn
            </h2>
          </div>
          <ul class="info_list unordered_list_block">
            <li>
              <i class="fas fa-check"></i>
              <span>
                Fermentum iaculis eu non diam phasellus vestibulum. Porta non pulvinar neque laoreet suspendisse. Justo nec ultrices dui sapien proin sed libero
              </span>
            </li>
            <li>
              <i class="fas fa-check"></i>
              <span>
                At consectetur lorem donec massa sapien. Pulvinar sapien et ligula ullamcorper malesuada proin
              </span>
            </li>
            <li>
              <i class="fas fa-check"></i>
              <span>
                Quisque id diam vel quam elementum pulvinar. Eget felis eget nunc lobortis mattis aliquam faucibus purus.
              </span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col col-lg-3 col-md-6">
        <div class="service_item" data-magnetic>
          <div class="item_icon">
            <img src="assets/images/icon/icon_desktop.svg" alt="Terces – Online Learning Platform">
          </div>
          <div class="item_content">
            <h3 class="item_title">Course Format</h3>
            <ul class="info_list unordered_list_block">
              <li>
                <i class="fas fa-square"></i>
                <span>Video Tutorials</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>Checking the Task</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>Pulvinar sapien</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>Software</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col col-lg-3 col-md-6">
        <div class="service_item" data-magnetic>
          <div class="item_icon">
            <img src="assets/images/icon/icon_calendar.svg" alt="Terces – Online Learning Platform">
          </div>
          <div class="item_content">
            <h3 class="item_title">Duration Course</h3>
            <ul class="info_list unordered_list_block">
              <li>
                <i class="fas fa-square"></i>
                <span>3 Weeks</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>5 Video Tutorials</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>3 Hours of Consultations</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>1.5 Hours Webinar</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Courses Info Section - End
        ================================================== -->

<!-- Course Deals Section - Start
        ================================================== -->
<section class="course_deals_section section_space_lg bg_light decoration_wrap overflow-hidden">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col col-lg-5 order-lg-last">
        <div class="image_widget">
          <img src="assets/images/about/about_image_5.jpg" alt="Terces – Online Learning Platform">
        </div>
      </div>
      <div class="col col-lg-6">
        <div class="content_wrap">
          <div class="section_heading">
            <h2 class="heading_text">
              Data Warehouse Concepts, Design, and Data Integration
            </h2>
            <p class="heading_description mb-0">
              Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Consectetur purus ut faucibus pulvinar elementum
            </p>
          </div>
          <div class="deals_countdown">
            <ul class="countdown_timer unordered_list" data-countdown="2023/12/31"></ul>
            <div class="discount_value">
              <strong>40%</strong>
              <span>Sale</span>
            </div>
          </div>
          <div class="btn_wrap pb-0">
            <a class="btn border_dark" href="course.html">
              <span>
                <small>Explore Courses</small>
                <small>Explore Courses</small>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="deco_item shape_img_1" data-parallax='{"y" : 130, "smoothness": 6}'>
    <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
  </div>
  <div class="deco_item shape_img_2" data-parallax='{"x" : -130, "smoothness": 6}'>
    <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
  </div>
  <div class="deco_item shape_img_3" data-parallax='{"y" : -130, "smoothness": 6}'>
    <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
  </div>
</section>
<!-- Course Deals Section - End
        ================================================== -->

<?= $this->partial("partials_courselist") ?>


<?php $this->partial("partials_newsletter")  ?>