<?php

use General\Service\GeneralService;
?>
<?= $this->headtitle("Business Analysis Program");
$f = new \NumberFormatter("en", NumberFormatter::SPELLOUT);
?>
<div id="bana">
    <!-- Page Section - Start
        ================================================== -->
    <input type="hidden" ref="programId" :value="<?= $data->getId() ?>">
    <input type="hidden" ref="puuuid" value=<?= $data->getUuid() ?>>
    <section class="page_banner">
        <div class="container">
            <div class="content_wrapper">
                <div class="row align-items-center">
                    <div class="col col-lg-7">
                        <ul class="breadcrumb_nav unordered_list">
                            <li><a href="">Home </a></li>
                            <li><a href="">Program</a></li>
                            <li><?= GeneralService::GENERAL_TRAINING_WORK_EXPERIENCE ?></li>
                        </ul>

                        <h1 class="page_title">
                            <?= $data->getTitle(); ?>
                        </h1>

                        <ul class="info_list unordered_list_block pb-0">
                            <?= $data->getDescription(); ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Page Section - End
        ================================================== -->

    <!-- Course Details Section - Start
        ================================================== -->
    <section class="details_section course_details_section">
        <div class="container">
            <div class="row">
                <div class="col col-lg-8">
                    <div class="section_space_lg pb-lg-0">
                        <div class="pe-lg-5">
                            <div class="course_info_card d-lg-none">
                                <div class="details_image">
                                    <img src="<?= $data->getBanner() ?>" alt="Terces – Online Learning Platform">
                                </div>

                                <div class="item_price">
                                    <span class="sale_price"><?= $this->currencyFormat($data->getCost(), "USD") ?></span>
                                </div>
                                <a data-toggle="modal" data-target="#modalPayment" class="btn btn_dark">
                                    <span>
                                        <small>Get Course</small>
                                        <small>Get Course</small>
                                    </span>
                                </a>




                                <ul class="course_info_list unordered_list_block">

                                    <li>
                                        <span><i class="fas fa-chart-user"></i> Pre-requisite</span>
                                        <strong><a href="<?= $this->url("application", ["action" => "business-analysis-masterclass"]) ?>"><?= GeneralService::GENERAL_TRAINING_FREE ?></a></strong>
                                    </li>

                                    <li>
                                        <span><i class="fas fa-chart-bar"></i> Level</span>
                                        <strong>Intermediate</strong>
                                    </li>
                                    <li>
                                        <span><i class="fas fa-clock"></i> Duration</span>
                                        <strong><?= $data->getDuration() ?></strong>
                                    </li>
                                    <li>
                                        <span><i class="fas fa-video"></i> Lessons</span>
                                        <strong> Video</strong>
                                    </li>


                                </ul>
                            </div>

                            <div class="section_heading">
                                <h2 class="heading_text">
                                    Course Content
                                </h2>
                            </div>

                            <?php $courseCount = 0;  ?>

                            <?php foreach ($data->getCourses() as $key => $course) :

                            ?>

                                <div class="accordion_wrap mb-3">
                                    <h3 class="details_info_title mb-2">Section <?= $key + 1 ?>. <?= $course->getTitle() ?>
                                        <?php if (count($course->getCourseResource())) : ?>
                                            <a data-toggle="modal" data-target="#modalCR<?= $course->getId() ?>" @click="getCResourse('<?= $course->getId() ?>')" href="javascript:;"> <i class="fas fa-paperclip"></i></a>
                                        <?php endif; ?>
                                    </h3>


                                    <div id="modalCR<?= $course->getId() ?>" class="modal fade">
                                        <div class="modal-dialog modal-dialog-vertical-center" role="document">
                                            <div class="modal-content bd-0 tx-14">
                                                <div class="modal-header">
                                                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">
                                                        Resources </h6>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body pd-25">

                                                    <div class="card card-body">
                                                        <ul v-if="courseResouces.length" class="info_list unordered_list_block">
                                                            <li v-for="res in courseResouces">
                                                                <a :href="res.resourceFile.imageUrl">
                                                                    <i class="fas fa-paperclip"></i>
                                                                    <span>{{res.resourceTitle}}</span>
                                                                </a>
                                                            </li>

                                                        </ul>
                                                    </div>


                                                </div>
                                                <div class="modal-footer">

                                                </div>
                                            </div>
                                        </div><!-- modal-dialog -->
                                    </div><!-- modal -->

                                    <div class="accordion style_2" id="corse_details_accordion_<?= ($key + 1) . str_replace(" ", "_", $course->getTitle()) ?>">
                                        <?php
                                        if (count($course->getCourseContent())) :
                                            foreach ($course->getCourseContent() as $ckey => $content) :
                                                $courseCount++;
                                        ?>

                                                <div class="accordion-item">
                                                    <div class="checkbox_item accordion_item_checked">
                                                        <input type="checkbox">
                                                    </div>
                                                    <div class="accordion-button collapsed" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_3_<?= ($ckey + 1) . str_replace(" ", "_", $course->getTitle()) ?>" aria-expanded="false">
                                                        Lesson <?= ($courseCount) . ":  ";
                                                                echo  $content->getTitle() ?>
                                                    </div>
                                                    <div id="collapse_3_<?= ($ckey + 1) . str_replace(" ", "_", $course->getTitle()) ?>" class="accordion-collapse collapse" data-bs-parent="#corse_details_accordion_<?= ($key + 1) . str_replace(" ", "_", $course->getTitle()) ?>">
                                                        <div class="accordion-body">
                                                            <p class="mb-3">
                                                                <?= $content->getDescription(); ?>
                                                            </p>
                                                            <div class="intro_video mb-3">
                                                                <div class="video_wrap">
                                                                    <img src="<?= $content->getBanner()->getImageUrl() ?>" alt="Terces – Online Learning Platform">

                                                                    <?php if ($this->isSubscribed($data->getId(), $courseCount)) : ?>
                                                                        <a class="video_play_btn popup_video" href="<?= $content->getVideo() ?>">
                                                                            <span class="icon"><i class="fas fa-play"></i></span>
                                                                        </a>
                                                                    <?php else : ?>
                                                                        <a class="video_play_btn popup_video" href="<?= $content->getSnippetVideo() ?>">
                                                                            <span class="icon"><i class="fas fa-play"></i></span>
                                                                        </a>
                                                                    <?php endif; ?>
                                                                </div>
                                                            </div>
                                                            <?php if (count($content->getResources()) > 0) : ?>
                                                                <a data-toggle="modal" data-target="#modalR<?= $content->getId() ?>" @click="getResourse('<?= $content->getId() ?>')" class="btn border_dark btn_small" href="#!">
                                                                    <span>
                                                                        <small><img src="assets/images/icon/icon_clip.svg" alt="Terces – Online Learning Platform">
                                                                            Resources</small>
                                                                        <small><img src="assets/images/icon/icon_clip_white.svg" alt="Terces – Online Learning Platform">
                                                                            Resources</small>
                                                                    </span>
                                                                </a>

                                                                <div id="modalR<?= $content->getId() ?>" class="modal fade">
                                                                    <div class="modal-dialog modal-dialog-vertical-center" role="document">
                                                                        <div class="modal-content bd-0 tx-14">
                                                                            <div class="modal-header">
                                                                                <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">
                                                                                    Resources </h6>
                                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                                    <span aria-hidden="true">&times;</span>
                                                                                </button>
                                                                            </div>
                                                                            <div class="modal-body pd-25">

                                                                                <div class="card card-body">
                                                                                    <ul v-if="aResources.length" class="info_list unordered_list_block">
                                                                                        <li v-for="res in aResources">
                                                                                            <a :href="res.resourceFile.imageUrl">
                                                                                                <i class="fas fa-paperclip"></i>
                                                                                                <span>{{res.resourceTitle}}</span>
                                                                                            </a>
                                                                                        </li>

                                                                                    </ul>
                                                                                </div>


                                                                            </div>
                                                                            <div class="modal-footer">

                                                                            </div>
                                                                        </div>
                                                                    </div><!-- modal-dialog -->
                                                                </div><!-- modal -->
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>

                                        <?php endforeach;
                                        endif;
                                        ?>
                                    </div>
                                </div>


                                <div class="row mb-4">
                                    <?php if ($course->getQuiz() != NULL) : ?>
                                        <div class="col">

                                            <button @click="getQuiz('<?= $course->getId() ?>')" data-toggle="modal" data-target="#modalQ<?= $course->getId() ?>" type="submit" class="btn btn_dark">
                                                <span>
                                                    <small>Quiz</small>
                                                    <small>Quiz</small>
                                                </span>
                                            </button>
                                        </div>
                                    <?php endif; ?>
                                </div>

                                <?php echo $this->partial("partial_quiz", ["course" => $course]) ?>
                            <?php endforeach; ?>



                        </div>
                    </div>
                </div>



                <div class="col col-lg-4">
                    <aside class="sidebar">
                        <div class="course_info_card d-none d-lg-block">
                            <div class="details_image">
                                <img src="<?= $data->getBanner() ?>" alt="Terces – Online Learning Platform">
                            </div>
                            <ul class="meta_info_list unordered_list">

                            </ul>
                            <div class="item_price">
                                <span class="sale_price"><?= $this->currencyFormat($data->getCost(), "USD") ?></span>
                            </div>
                            <a data-toggle="modal" data-target="#modalPayment" class="btn btn_dark">
                                <span>
                                    <small>Get Course</small>
                                    <small>Get Course</small>
                                </span>
                            </a>
                            <ul class="course_info_list unordered_list_block">
                                <li>
                                    <span><i class="fas fa-user"></i> Pre-requisite</span>
                                    <strong><a href="<?= $this->url("application", ["action" => "business-analysis-masterclass"]) ?>"><?= GeneralService::GENERAL_TRAINING_FREE ?>s</a></strong>
                                </li>
                                <li>
                                    <span><i class="fas fa-chart-bar"></i> Level</span>
                                    <strong>Intermediate</strong>
                                </li>
                                <li>
                                    <span><i class="fas fa-clock"></i> Duration</span>
                                    <strong><?= $this->data->getDuration() ?></strong>
                                </li>
                                <li>
                                    <span><i class="fas fa-video"></i> Lessons</span>
                                    <strong>Video</strong>
                                </li>

                            </ul>
                        </div>

                        <div class="callbox_wrap">
                            <h3 class="widget_title">Schedule your internship</h3>
                            <a class="btn border_dark w-100" href="<?= $this->url("application", ["action" => 'internship']); ?>">
                                <span>
                                    <small>Click To Schedule</small>
                                    <small>Click To Schedule</small>
                                </span>
                            </a>
                            <!--  <a class="btn btn_dark w-100" href="">
                                <span>
                                    <small>See Whole Course</small>
                                    <small>See Whole Course</small>
                                </span>
                            </a> -->
                        </div>


                    </aside>
                </div>
            </div>
        </div>
    </section>
    <!-- Course Details Section - End
        ================================================== -->
    <div id="modalPayment" class="modal fade">
        <div class="modal-dialog modal-dialog-vertical-center" role="document">
            <div class="modal-content bd-0 tx-14">
                <div class="modal-header">
                    <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">
                        Payment</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body pd-25">

                    <div class="card card-body">
                        <div v-if="isInteracPayment" class="callbox_wrap">
                            <?php if ($this->identity() != NULL) :  ?>
                                <ul class="info_list unordered_list_block text-start">
                                    <li>
                                        <i class="fas fa-caret-right"></i>
                                        <span>Transfer the equivalent to interac account <strong>Emuveyanoghenetejiri@gmail.com</strong></span>
                                    </li>
                                    <li>
                                        <i class="fas fa-caret-right"></i>
                                        <span>Fill and submit the Payment form </span>
                                    </li>
                                    <!-- <li>
                                        <i class="fas fa-caret-right"></i>
                                        <span>Checking 5 Homework</span>
                                    </li>
                                    <li>
                                        <i class="fas fa-caret-right"></i>
                                        <span>Mentor Consultation </span>
                                    </li>-->
                                </ul>
                                <div class="form_item">
                                    <input v-model="interac_amount" type="email" name="email" placeholder="Amount Paid">
                                </div>
                                <div class="form_item">
                                    <input v-model="interac_email" type="email" name="email" placeholder="Email Payment From">
                                </div>
                                <button :disabled="isSendingInterac" @click="confirmInteracPayment()" type="submit" class="btn btn_dark mb-5">
                                    <span>
                                        <small>Confirm Payment</small>
                                        <small>Confirm Payment</small>
                                    </span>
                                </button>
                            <?php else : ?>
                                <a class="btn btn_dark w-100" href="<?= $this->url("login")  ?>">
                                    <span>
                                        <small>Login</small>
                                        <small>Login</small>
                                    </span>
                                </a>
                            <?php endif; ?>
                        </div>

                        <div v-else class="callbox_wrap">
                            <div class="form_item">
                                <input v-model="coupon" type="text" placeholder="Coupon">
                            </div>
                            <!--   <h3 class="widget_title">Get More Benefits with Our Plans</h3> -->
                            <a class="btn border_dark w-100" :href="generateBuyNowUrl()">
                                <span>
                                    <small>Pay Once (USD)</small>
                                    <small>Pay Once (USD)</small>
                                </span>
                            </a>
                            <a class="btn btn_dark w-100" href="<?= ($this->identity() == NULL ? $this->url("login") : $this->url("application", ["action" => "generate-installments", "id" => $this->identity()->getUuid()], [
                                                                    'query' => [
                                                                        'cuuid' => $data->getUuid(),
                                                                    ],
                                                                ])) ?>">
                                <span>
                                    <small>Pay 4 installments (USD)</small>
                                    <small>Pay 4 installments (USD)</small>
                                </span>
                            </a>
                            <button class="btn btn_dark w-100" @click="toggleinterac()">
                                <span>
                                    <small>Pay with Interac (USD)</small>
                                    <small>Pay with Interac (USD)</small>
                                </span>
                            </button>
                            <a class="btn border_dark w-100" href="<?= $this->url("application", ["action" => "buy-course-naira", "id" => $data->getUuid()]) ?>">
                                <span>
                                    <small>Pay in Naira</small>
                                    <small>Pay in Naira</small>
                                </span>
                            </a>
                        </div>

                    </div>



                </div>
                <div class="modal-footer">

                </div>
            </div>
        </div><!-- modal-dialog -->
    </div><!-- modal -->
</div>
<script>
    const bana = Vue.createApp({
        data() {
            return {
                aResources: [],
                courseResouces: [],
                isInteracPayment: false,
                // ll: "Pleee",
                quizList: [],
                quizCountInit: 0,
                questionCount: 0,
                // activeQuizPage:0
                isSendingInterac: false,
                interac_amount: "",
                interac_email: "",

                coupon: "",
            }
        },

        mounted() {
            this.generateBuyNowUrl();
        },

        methods: {

            generateBuyNowUrl() {
                let vvv = '<?= $data->getUuid() ?>';
                let vrr = this.coupon;
                if (vrr != "") {
                    return `/buy-course/${vvv}?poc=${vrr}`;
                } else {
                    return `/buy-course/${vvv}`;
                }


                // alert(this.$refs.puuuid.value);
            },

            toggleinterac() {
                this.isInteracPayment = !this.isInteracPayment;
            },

            checkAnswer() {

            },

            quizNextPage() {

                this.quizCountInit++;
            },
            quizPreviousPage() {
                this.quizCountInit--;
            },
            getResourse(courseContentId = "") {

                // this.isFetchingResources = true;
                // this.activeCourseContent = courseContentId;
                axios.get(`/admin/get-content-resources/${courseContentId}`).then((result) => {
                    if (result.status == 200) {
                        // this.isFetchingResources = false;
                        this.aResources = result.data.data;
                    }
                }).catch((err) => {
                    Swal.fire({
                        icon: "error",
                        title: "An error occured",
                        text: err.response.data.message,
                    });
                });
            },

            getCResourse(courseContentId = "") {

                // this.isFetchingResources = true;
                // this.activeCourseContent = courseContentId;
                axios.get(`/admin/get-course-resources/${courseContentId}`).then((result) => {
                    if (result.status == 200) {
                        // this.isFetchingResources = false;
                        this.courseResouces = result.data.data;
                    }
                }).catch((err) => {
                    Swal.fire({
                        icon: "error",
                        title: "An error occured",
                        text: err.response.data.message,
                    });
                });
            },


            getQuiz(courseid) {

                axios.get(`/get-quiz/${courseid}`).then((result) => {
                    if (result.status == 200) {
                        this.quizList = result.data.data;
                        this.questionCount = this.quizList[0].questions.length;
                    }

                }).catch((err) => {
                    Swal.fire({
                        icon: "error",
                        title: "An error occured",
                        text: err.response.data.message,
                    });
                });
            },

            submitQuiz(courseid) {

            },

            confirmInteracPayment() {
                this.isSendingInterac = true;
                if (this.interac_amount == "" || this.interac_email == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Empty Field",
                        text: "A required field is empty"
                    });
                } else {
                    let formData = new FormData();
                    formData.append("email", this.interac_email);
                    formData.append("amount", this.interac_amount);
                    formData.append("program", this.$refs.programId.value);
                    axios.post("/app/send-interac", formData).then((result) => {
                        if (result.status == 201) {
                            Swal.fire({
                                icon: "success",
                                title: "Payment Sent",
                                text: "A payment confirmation request has been sent to administrator. We should have processed your payment in about 2 working days"
                            }).then(result => {

                                if (result.isConfirmed) {
                                    window.location.reload()
                                }
                            });
                            this.isSendingInterac = false;
                        }

                    }).catch((err) => {
                        Swal.fire({
                            icon: "error",
                            title: "Ooops",
                            text: "Somthing went wrong"
                        });
                        this.isSendingInterac = false;
                    });
                }
            },
        },
    });
    bana.mount("#bana")
</script>