<?php

use General\Service\GeneralService;
?>
<!-- Page Section - Start
        ================================================== -->
<section class="page_banner">
    <div class="container">
        <div class="content_wrapper">
            <div class="row align-items-center">
                <div class="col col-lg-7">
                    <ul class="breadcrumb_nav unordered_list">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="course.html">Course</a></li>
                        <li><?= GeneralService::GENERAL_TRAINING_FREE ?></li>
                    </ul>
                    <h1 class="page_title">
                        Begin Your Business Analysis Journey
                    </h1>
                    <ul class="meta_info_list unordered_list">
                        <li>
                            <i class="fas fa-chart-bar"></i>
                            <span>Beginner</span>
                        </li>
                        <li>
                            <i class="fas fa-clock"></i>
                            <span>2 Hours</span>
                        </li>
                        <!--<li>
                      <i class="fas fa-star"></i>
                      <span>3.5 (3k reviews)</span>
                    </li>-->
                    </ul>
                    <ul class="btns_group unordered_list">
                        <li>
                            <div class="item_price">
                                <del class="remove_price">$1000</del>
                                <span class="sale_price">Free</span>
                            </div>
                        </li>
                        <li>
                            <a href="<?= $this->url("register") ?>" class="btn btn_dark">
                                <span>
                                    <small>Register Now</small>
                                    <small>Register Now</small>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col col-lg-5">
                    <div class="image_widget page_banner_image">
                        <img src="assets/images/2.png" alt="Terces – Online Learning Platform">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page Section - End
        ================================================== -->

<!-- Courses Info Section - Start
        ================================================== -->
<section class="details_section courses_info_section section_space_lg">
    <div class="container">
        <div class="row">
            <div class="col col-lg-6">
                <div class="content_wrap">
                    <div class="section_heading">
                        <h2 class="heading_text mb-0">
                            What You will Learn
                        </h2>
                    </div>
                    <ul class="info_list unordered_list_block">
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Introduction to Business analysis
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                The business analyst
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analyst responsibilities in a project
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Qualifications of a business analyst
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analyst core concept model
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analysis knowledge areas
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Core skills of a business analyst
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col col-lg-3 col-md-6">
                <div class="service_item" data-magnetic>
                    <div class="item_icon">
                        <img src="assets/images/icon/icon_desktop.svg" alt="Terces – Online Learning Platform">
                    </div>
                    <div class="item_content">
                        <h3 class="item_title">Course Details</h3>
                        <ul class="info_list unordered_list_block">
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Zoom/Video Tutorials</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>20% Voucher</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Free Resources</span>
                            </li>

                            <li>
                                <i class="fas fa-square"></i>
                                <span>Self Paced</span>
                            </li>

                            <li>
                                <i class="fas fa-square"></i>
                                <span>Access to Terces Job portal</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col col-lg-3 col-md-6">
                <div class="service_item" data-magnetic>
                    <div class="item_icon">
                        <img src="assets/images/icon/icon_calendar.svg" alt="Terces – Online Learning Platform">
                    </div>
                    <div class="item_content">
                        <h3 class="item_title">Duration Course</h3>
                        <ul class="info_list unordered_list_block">
                            <li>
                                <i class="fas fa-square"></i>
                                <span>3 Hours</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Zoom/Video</span>
                            </li>
                            <!--<li>
                <i class="fas fa-square"></i>
                <span>3 Hours of Consultations</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>1.5 Hours Webinar</span>
              </li> -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<?= $this->partial("partials_coming_free_training") ?>
<?= $this->partial("partials_courselist") ?>


<?php $this->partial("partials_newsletter")  ?>