  <?php echo $this->headtitle("Buy Course") ?>

  <!-- Call To Action Section - Start
        ================================================== -->
  <section class="calltoaction_section section_space_lg bg_dark decoration_wrap">
      <div class="container">
          <div class="row align-items-center">
              <div class="col col-lg-7">
                  <div class="section_heading mb-lg-0">
                      <h2 class="heading_text text-white">
                          To Help You Choose the Right Course, You Need to Book a Consultation
                      </h2>
                      <p class="heading_description mb-0 text-white">
                          Varius morbi enim nunc faucibus. Eget nunc lobortis mattis aliquam faucibus purus in massa. Diam sit amet nisl suscipit adipiscing bibendum est.
                      </p>
                  </div>
              </div>
              <div class="col col-lg-5">
                  <div class="calltoaction_form">
                      <form action="#">
                          <h3 class="form_title">Get a Consultation</h3>
                          <div class="form_item">
                              <label for="input_name" class="input_title text-uppercase">Name</label>
                              <input id="input_name" type="text" name="name" placeholder="Input Name">
                          </div>
                          <div class="form_item">
                              <label for="input_email" class="input_title text-uppercase">Email</label>
                              <input id="input_email" type="email" name="email" placeholder="Input Email">
                          </div>
                          <div class="form_item">
                              <label for="input_question" class="input_title text-uppercase">Message</label>
                              <textarea id="input_question" name="Message" placeholder="Input Your Question"></textarea>
                          </div>
                          <button type="submit" class="btn btn_dark w-100">
                              <span>
                                  <small>Get a Consultation</small>
                                  <small>Get a Consultation</small>
                              </span>
                          </button>
                      </form>
                  </div>
              </div>
          </div>
      </div>
     
  </section>
  <!-- Call To Action Section - End
        ================================================== -->