<?= $this->headtitle("Career Service") ?>
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<!-- Popular Event Section - Start
        ================================================== -->
<section class="popular_event_section section_space_lg bg_dark decoration_wrap">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-7">
                <div class="section_heading mb-lg-0">
                    <h2 class="heading_text text-white">
                        Schedule A Service
                    </h2>
                    <p class="heading_description mb-0 text-white">
                        <!--  Rhoncus dolor purus non enim praesent elementum facilisis. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Iaculis eu non diam phasellus vestibulum lorem sed risus. -->
                    </p>

                </div>
            </div>
            <div class="col col-lg-5">
                <div class="popular_event_list">
                    <h3 class="wrap_title">Schedule a Service</h3>
                    <ul class="unordered_list_block">



                        <li>
                            <div class="column">
                                <b class="day">00</b>

                            </div>
                            <div class="column">
                                <!-- Calendly link widget begin -->
                                <a href="" class="btn btn_primary btn_sm" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/app-t-academy/30-min-resume-review-writing-nigeria'});return false;">Schedule Resume Review</a>
                                <!-- Calendly link widget end -->
                                <!-- Calendly badge widget end -->
                                <br>
                                In this session, the career coach will reveiew you resume and work with you to build an updated resume that matches your desired role


                            </div>
                        </li>


                        <li>
                            <div class="column">
                                <b class="day">00</b>

                            </div>
                            <div class="column">

                                <!-- Calendly link widget begin -->
                                <a href="" class="btn btn_primary btn_sm" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/app-t-academy/30min-interview-prep-session'});return false;">Schedule Interview Prep</a>
                                <!-- Calendly link widget end -->

                                <br>
                                In this session, the career coach will prepare you with interview question for your upcoming interview

                                <span class="event_name">
                                    <strong>Prepare for:</strong> <small>Lora Hill</small>
                                </span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="deco_item shape_img_1" data-parallax='{"y" : 130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
    <div class="deco_item shape_img_2" data-parallax='{"x" : -130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
    <div class="deco_item shape_img_3" data-parallax='{"y" : -130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
</section>
<!-- Popular Event Section - End
        ================================================== -->