<!-- Page Section - Start
        ================================================== -->
<section class="page_banner">
    <div class="container">
        <div class="content_wrapper" style="background-image: url('/assets/images/2.png');">
            <div class="row align-items-center">
                <div class="col col-lg-6">
                    <ul class="breadcrumb_nav unordered_list">
                        <li><a href="index.html">Home</a></li>
                        <li>Contact Us</li>
                    </ul>
                    <h1 class="page_title">Contacts</h1>
                  
                    
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page Section - End
        ================================================== -->

<!-- Contact Form Section - Start
        ================================================== -->
<section class="contact_form_section section_space_lg bg_light decoration_wrap overflow-hidden">
    <div class="container decoration_wrap">
        <div class="row justify-content-center">
            <div class="col col-lg-7">
                <div class="section_heading text-center">
                    <h2 class="heading_text mb-0">
                        Contact Our Support Team to Know What You Want
                    </h2>
                </div>
            </div>
        </div>

        <form action="#">
            <div class="row justify-content-center">
                <div class="col col-lg-8">
                    <div class="row">
                        <div class="col col-md-6">
                            <div class="form_item m-0">
                                <label for="input_name" class="input_title">Name</label>
                                <input id="input_name" type="text" name="name" placeholder="Your Name">
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form_item m-0">
                                <label for="input_email" class="input_title">Email</label>
                                <input id="input_email" type="email" name="email" placeholder="Your Email">
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form_item m-0">
                                <label for="input_phone" class="input_title">Phone</label>
                                <input id="input_phone" type="tel" name="telephone" placeholder="Your Phone">
                            </div>
                        </div>
                        <div class="col col-md-6">
                            <div class="form_item m-0">
                                <label for="input_jubject" class="input_title">Subject</label>
                                <select name="subject" id="input_jubject">
                                  <!--  <option value="subject" selected>Choose Subject</option> -->
                                    <option value="training">Training</option>
                                    <option value="payment">Payment</option>
                                    
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form_item">
                                <label for="input_message" class="input_title">Message</label>
                                <textarea id="input_message" name="message" placeholder="Type Your Message"></textarea>
                            </div>
                            <button type="submit" class="btn btn_dark w-100 b-block">
                                <span>
                                    <small>Send Your Message</small>
                                    <small>Send Your Message</small>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="deco_item shape_img_1 wow fadeInUp" data-wow-delay=".2s">
            <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
        </div>
        <div class="deco_item shape_img_2 wow fadeInUp" data-wow-delay=".4s">
            <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
        </div>
    </div>

    <div class="deco_item shape_img_3 wow fadeInLeft" data-wow-delay=".2s">
        <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
    </div>
    <div class="deco_item shape_img_4 wow fadeInRight" data-wow-delay=".4s">
        <img src="assets/images/shape/shape_img_7.png" alt="Terces – Online Learning Platform">
    </div>
</section>
<!-- Contact Form Section - End
        ================================================== -->

<?= $this->partial("partials_newsletter"); ?>