<!-- Banner Section - Start
  ================================================== -->
<section class="hero_banner style_1">
    <div class="container">
        <div class="content_wrap">
            <div class="row">
                <div class="col col-lg-7">
                    <h1 class="banner_small_title">Business Analysis Masterclass</h1>
                    <h2 class="banner_big_title">Create value with Business Analysis</h2>
                    <p class="banner_description">
                        Increase your value as a business analyst, earn six figures, optimize youself
                    </p>
                    <ul class="banner_btns_group unordered_list">
                        <li>
                            <a class="btn btn_primary" href="#">
                                <span>
                                    <small>Free Training</small>
                                    <small>Register</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="video_play_btn text-white popup_video" href="https://www.youtube.com/watch?v=7e90gBu4pas">
                                <span class="icon" data-magnetic><i class="fas fa-play"></i></span>
                                <span class="text">Watch video</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col col-lg-5">
                    <div class="banner_image_1 decoration_wrap">
                        <div class="image_wrap">
                            <img src="/assets/images/1.png" alt=" Terceså – Online Learning Platform">
                        </div>

                        <!-- <div class="deco_item shape_img_1" data-parallax='{"y" : -130, "smoothness": 6}'>
                            <img src="assets/images/shape/shape_img_1.png" alt="Terces – Online Learning Platform">
                        </div>
                        <div class="deco_item shape_img_2" data-parallax='{"y" : 160, "smoothness": 6}'>
                            <img src="assets/images/shape/shape_img_2.png" alt="Terces – Online Learning Platform">
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section - End
  ================================================== -->


<?= $this->partial("partials_coming_free_training") ?>

<!-- Expect From Course - Start
  ================================================== -->
<section class="expect_from_course section_space_lg">
    <div class="container">
        <div class="row">
            <div class="col col-lg-6">
                <div class="section_heading">
                    <h2 class="heading_text">
                        What to Expect
                    </h2>
                    <p class="heading_description mb-0">
                        <!-- Rutrum tellus pellentesque eu tincidunt. Venenatis cras sed felis eget velit aliquet sagittis id consectetur -->
                    </p>
                </div>

                <div class="image_widget">
                    <img src="assets/images/home1.jpeg" alt="Terces – Online Learning Platform">
                </div>
            </div>
            <div class="col col-lg-6">
                <!-- Button will hide on Mobile Device -->
                <div class="btn_wrap pt-0 d-none d-lg-flex justify-content-end">
                    <a class="btn border_dark" href="course.html">
                        <span>
                            <small>Explore Courses</small>
                            <small>Explore Courses</small>
                        </span>
                    </a>
                </div>

                <div class="row">
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_academic_cap.svg" alt="Terces – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Personal Mentoring</h3>
                                <p class="mb-0">
                                    Providing one on one and personal mentoring for securing a business analysis job,
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_physics.svg" alt="Terces – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Job Opportunity</h3>
                                <p class="mb-0">
                                    You will have exclusive access to a pool of availaible Business Analysis Jobs on Terces Jobs Platform
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_communication.svg" alt="Terces – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Hands on Projects</h3>
                                <p class="mb-0">
                                    Here you would learn about global projects like the Anti money laundering project
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_diploma.svg" alt="Terces – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Internship opportunity</h3>
                                <p class="mb-0">
                                    1 month internship -ability to intern with terces consulting and get the canadian work experience you desire
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Button will show on Mobile Device -->
                <div class="btn_wrap pb-0 d-block d-lg-none text-center">
                    <a class="btn border_dark" href="course.html">
                        <span>
                            <small>Explore Courses</small>
                            <small>Explore Courses</small>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Expect From Course - End
  ================================================== -->

<!-- Advertisement Section - Start
  ================================================== -->
<section class="advertisement_section bg_dark">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-6">
                <div class="section_heading mb-lg-0">
                    <h2 class="heading_text text-white">
                        Take the Next Step Toward Your Personal and Professional Goals
                    </h2>
                    <p class="heading_description mb-0 text-white">
                        <!--  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. -->
                    </p>
                    <div class="btn_wrap pb-0">
                        <a class="btn btn_primary" href="<?= $this->url("application", ["action" => "all-course"]) ?>">


                            <span>
                                <small>Explore Courses</small>
                                <small>Explore Courses</small>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col col-lg-6">
                <div class="row images_group decoration_wrap">
                    <div class="col col-md-6 col-sm-6">
                        <div class="image_wrap">
                            <img src="assets/images/33.png" alt="Terces – Online Learning Platform">
                        </div>
                        <div class="image_wrap">
                            <img src="assets/images/1.png" alt="Terces  – Online Learning Platform">
                        </div>
                    </div>
                    <div class="col col-md-6 col-sm-6">
                        <div class="image_wrap">
                            <img src="assets/images/2.png" alt="Terces  – Online Learning Platform">
                        </div>
                        <div class="image_wrap">
                            <img src="assets/images/4.png" alt="Terces  – Online Learning Platform">
                        </div>
                    </div>
                    <!--<div class="deco_item shape_img_1" data-parallax='{"y" : -130, "smoothness": 6}'>
                        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
                    </div>
                    <div class="deco_item shape_img_2" data-parallax='{"y" : 130, "smoothness": 6}'>
                        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
                    </div>-->
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Advertisement Section - End
  ================================================== -->

<!-- Courses Info Section - Start
  ================================================== -->
<section class="courses_info_section section_space_lg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-6">
                <div class="image_widget">
                    <img src="assets/images/5.png" alt="Terces – Online Learning Platform">
                </div>
            </div>
            <div class="col col-lg-6">
                <div class="content_wrap ps-lg-3">
                    <div class="section_heading">
                        <h2 class="heading_text">
                            Programs
                        </h2>
                        <p class="heading_description mb-0">
                            <!-- Rutrum tellus pellentesque eu tincidunt. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Sit amet porttitor eget dolor morbi -->
                        </p>
                    </div>
                    <ul class="info_list unordered_list_block">
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Business Analysis Masterclass (free)
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Business Analysis Hands-On Program (Paid)
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Business analysis Certification Program (Paid)
                            </span>
                        </li>

                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Business Analysis On job Support (Paid)
                            </span>
                        </li>
                    </ul>
                    <div class="btn_wrap pb-0">
                        <a class="btn btn_dark" href="mentor.html">
                            <span>
                                <small>Register Now</small>
                                <small>Register Now</small>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Courses Info Section - End
  ================================================== -->

<?= $this->partial("partials_newsletter"); ?>