<!-- Banner Section - Start
  ================================================== -->
<section class="hero_banner style_1">
    <div class="container">
        <div class="content_wrap">
            <div class="row">
                <div class="col col-lg-7">
                    <h1 class="banner_small_title">Business Analysis Masterclass</h1>
                    <h2 class="banner_big_title">Create value with Business Analysis</h2>
                    <p class="banner_description">
                        Increase your value as a business analyst, earn six figures, optimize youself
                    </p>
                    <ul class="banner_btns_group unordered_list">
                        <li>
                            <a class="btn btn_primary" href="#">
                                <span>
                                    <small>Free Training</small>
                                    <small>Register</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="video_play_btn text-white popup_video" href="https://www.youtube.com/watch?v=7e90gBu4pas">
                                <span class="icon" data-magnetic><i class="fas fa-play"></i></span>
                                <span class="text">Watch video</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col col-lg-5">
                    <div class="banner_image_1 decoration_wrap">
                        <div class="image_wrap">
                            <img src="assets/images/banner/hero_banner_img_1.jpg" alt="Collab – Online Learning Platform">
                        </div>

                        <div class="deco_item shape_img_1" data-parallax='{"y" : -130, "smoothness": 6}'>
                            <img src="assets/images/shape/shape_img_1.png" alt="Collab – Online Learning Platform">
                        </div>
                        <div class="deco_item shape_img_2" data-parallax='{"y" : 160, "smoothness": 6}'>
                            <img src="assets/images/shape/shape_img_2.png" alt="Collab – Online Learning Platform">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section - End
  ================================================== -->

<!-- Expect From Course - Start
  ================================================== -->
<section class="expect_from_course section_space_lg">
    <div class="container">
        <div class="row">
            <div class="col col-lg-6">
                <div class="section_heading">
                    <h2 class="heading_text">
                        What to Expect
                    </h2>
                    <p class="heading_description mb-0">
                        <!-- Rutrum tellus pellentesque eu tincidunt. Venenatis cras sed felis eget velit aliquet sagittis id consectetur -->
                    </p>
                </div>

                <div class="image_widget">
                    <img src="assets/images/home1.jpeg" alt="Terces – Online Learning Platform">
                </div>
            </div>
            <div class="col col-lg-6">
                <!-- Button will hide on Mobile Device -->
                <div class="btn_wrap pt-0 d-none d-lg-flex justify-content-end">
                    <a class="btn border_dark" href="course.html">
                        <span>
                            <small>Explore Courses</small>
                            <small>Explore Courses</small>
                        </span>
                    </a>
                </div>

                <div class="row">
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_academic_cap.svg" alt="Terces – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Personal Mentoring</h3>
                                <p class="mb-0">
                                    Providing one on one and personal mentoring for securing a business analysis job,
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_physics.svg" alt="Collab – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Job Opportunity</h3>
                                <p class="mb-0">
                                    You will have exclusive access to a pool of availaible Business Analysis Jobs on Terces Jobs Platform
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_communication.svg" alt="Collab – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Hands on Projects</h3>
                                <p class="mb-0">
                                    Here you would learn about global projects like the Anti money laundering project
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col col-md-6">
                        <div class="service_item" data-magnetic>
                            <div class="item_icon">
                                <img src="assets/images/service/icon_diploma.svg" alt="Collab – Online Learning Platform">
                            </div>
                            <div class="item_content">
                                <h3 class="item_title">Internship opportunity</h3>
                                <p class="mb-0">
                                    1 month internship -ability to intern with terces consulting and get the canadian work experience you desire
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Button will show on Mobile Device -->
                <div class="btn_wrap pb-0 d-block d-lg-none text-center">
                    <a class="btn border_dark" href="course.html">
                        <span>
                            <small>Explore Courses</small>
                            <small>Explore Courses</small>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Expect From Course - End
  ================================================== -->

<!-- Courses Section - Start
  ================================================== -->
<section class="courses_section section_space_lg">
    <div class="container">
        <div class="section_heading">
            <div class="row align-items-center justify-content-lg-between">
                <div class="col col-lg-6">
                    <h2 class="heading_text mb-0">
                        Highest Rated Online Courses
                    </h2>
                </div>
                <div class="col col-lg-5">
                    <p class="heading_description mb-0 text-lg-end">
                        Dignissim enim sit amet venenatis urna cursus eget nunc. Egestas sed sed risus pretium quam vulputate
                    </p>
                </div>
            </div>
        </div>

        <div class="tabs_wrapper">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <button class="active" data-bs-toggle="tab" data-bs-target="#teb_hr" type="button" role="tab" aria-selected="true">
                        <i class="fas fa-users"></i>
                        <span>Business Analysis</span>
                    </button>
                </li>
                
                <li role="presentation">
                    <button data-bs-toggle="tab" data-bs-target="#teb_design" type="button" role="tab" aria-selected="false">
                        <i class="fas fa-palette"></i>
                        <span>Design</span>
                    </button>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="teb_hr" role="tabpanel">
                    <div class="row">
                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_1.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Computer Science</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$29.99</span>
                                            <del class="remove_price">$39.99</del>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Programming for Everybody (Getting Started with Python)
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_2.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Photography</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$9.99</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Photography Masterclass: A Complete Guide to Photography
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_3.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Business</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">FREE</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Project Management Principles and Practices
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="teb_photography" role="tabpanel">
                    <div class="row">
                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_1.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Computer Science</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$29.99</span>
                                            <del class="remove_price">$39.99</del>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Programming for Everybody (Getting Started with Python)
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_2.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Photography</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$9.99</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Photography Masterclass: A Complete Guide to Photography
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_3.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Business</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">FREE</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Project Management Principles and Practices
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="teb_programming" role="tabpanel">
                    <div class="row">
                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_1.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Computer Science</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$29.99</span>
                                            <del class="remove_price">$39.99</del>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Programming for Everybody (Getting Started with Python)
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_2.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Photography</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$9.99</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Photography Masterclass: A Complete Guide to Photography
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_3.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Business</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">FREE</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Project Management Principles and Practices
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="teb_marketing" role="tabpanel">
                    <div class="row">
                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_1.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Computer Science</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$29.99</span>
                                            <del class="remove_price">$39.99</del>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Programming for Everybody (Getting Started with Python)
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_2.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Photography</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$9.99</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Photography Masterclass: A Complete Guide to Photography
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_3.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Business</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">FREE</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Project Management Principles and Practices
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="teb_design" role="tabpanel">
                    <div class="row">
                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_1.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Computer Science</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$29.99</span>
                                            <del class="remove_price">$39.99</del>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Programming for Everybody (Getting Started with Python)
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_2.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Photography</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">$9.99</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Photography Masterclass: A Complete Guide to Photography
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class="col col-lg-4">
                            <div class="course_card">
                                <div class="item_image">
                                    <a href="course_details.html" data-cursor-text="View">
                                        <img src="assets/images/course/course_image_3.jpg" alt="Collab – Online Learning Platform">
                                    </a>
                                </div>
                                <div class="item_content">
                                    <div class="d-flex align-items-center justify-content-between mb-3">
                                        <ul class="item_category_list unordered_list">
                                            <li><a href="#!">Business</a></li>
                                        </ul>
                                        <div class="item_price">
                                            <span class="sale_price">FREE</span>
                                        </div>
                                    </div>
                                    <ul class="meta_info_list unordered_list">
                                        <li>
                                            <i class="fas fa-chart-bar"></i>
                                            <span>Beginner</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-clock"></i>
                                            <span>120 Hours</span>
                                        </li>
                                        <li>
                                            <i class="fas fa-star"></i>
                                            <span>3.5 (3k reviews)</span>
                                        </li>
                                    </ul>
                                    <h3 class="item_title">
                                        <a href="course_details.html">
                                            Project Management Principles and Practices
                                        </a>
                                    </h3>
                                    <a class="btn_unfill" href="course_details.html">
                                        <span class="btn_text">View Course</span>
                                        <span class="btn_icon">
                                            <i class="fas fa-long-arrow-right"></i>
                                            <i class="fas fa-long-arrow-right"></i>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Courses Section - End
  ================================================== -->

<!-- Advertisement Section - Start
  ================================================== -->
<section class="advertisement_section bg_dark">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-6">
                <div class="section_heading mb-lg-0">
                    <h2 class="heading_text text-white">
                        Take the Next Step Toward Your Personal and Professional Goals
                    </h2>
                    <p class="heading_description mb-0 text-white">
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    </p>
                    <div class="btn_wrap pb-0">
                        <a class="btn btn_primary" href="course.html">
                            <span>
                                <small>Explore Courses</small>
                                <small>Explore Courses</small>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col col-lg-6">
                <div class="row images_group decoration_wrap">
                    <div class="col col-md-6 col-sm-6">
                        <div class="image_wrap">
                            <img src="assets/images/advertisement/advertisement_img_1.jpg" alt="Collab – Online Learning Platform">
                        </div>
                        <div class="image_wrap">
                            <img src="assets/images/advertisement/advertisement_img_2.jpg" alt="Collab – Online Learning Platform">
                        </div>
                    </div>
                    <div class="col col-md-6 col-sm-6">
                        <div class="image_wrap">
                            <img src="assets/images/advertisement/advertisement_img_3.jpg" alt="Collab – Online Learning Platform">
                        </div>
                        <div class="image_wrap">
                            <img src="assets/images/advertisement/advertisement_img_4.jpg" alt="Collab – Online Learning Platform">
                        </div>
                    </div>
                    <div class="deco_item shape_img_1" data-parallax='{"y" : -130, "smoothness": 6}'>
                        <img src="assets/images/shape/shape_img_3.png" alt="Collab – Online Learning Platform">
                    </div>
                    <div class="deco_item shape_img_2" data-parallax='{"y" : 130, "smoothness": 6}'>
                        <img src="assets/images/shape/shape_img_3.png" alt="Collab – Online Learning Platform">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Advertisement Section - End
  ================================================== -->

<!-- Courses Info Section - Start
  ================================================== -->
<section class="courses_info_section section_space_lg">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-6">
                <div class="image_widget">
                    <img src="assets/images/about/about_image_2.jpg" alt="Collab – Online Learning Platform">
                </div>
            </div>
            <div class="col col-lg-6">
                <div class="content_wrap ps-lg-3">
                    <div class="section_heading">
                        <h2 class="heading_text">
                            Supporting Student Learning in Your Course
                        </h2>
                        <p class="heading_description mb-0">
                            Rutrum tellus pellentesque eu tincidunt. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Sit amet porttitor eget dolor morbi
                        </p>
                    </div>
                    <ul class="info_list unordered_list_block">
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Learn in-demand skills with over 183,000 video courses
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Choose courses taught by real-world experts
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-square"></i>
                            <span>
                                Learn at your own pace, with lifetime access on mobile and desktop
                            </span>
                        </li>
                    </ul>
                    <div class="btn_wrap pb-0">
                        <a class="btn btn_dark" href="mentor.html">
                            <span>
                                <small>Our Mentors</small>
                                <small>Our Mentors</small>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Courses Info Section - End
  ================================================== -->

<?= $this->partial("partials_newsletter"); ?>
