<?php $this->headtitle("internship - On Job Training"); ?>

<!-- Popular Event Section - Start
        ================================================== -->
<section id="kki" class="popular_event_section section_space_lg bg_dark decoration_wrap">
    <div class="container">
        <div class="row align-items-center">
            <div class="col col-lg-7">
                <div class="section_heading mb-lg-0">
                    <h2 class="heading_text text-white">
                        Select an internship Cohort
                    </h2>
                    <p class="heading_description mb-0 text-white">
                        <!--  Rhoncus dolor purus non enim praesent elementum facilisis. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Iaculis eu non diam phasellus vestibulum lorem sed risus. -->
                    </p>

                </div>
            </div>
            <div class="col col-lg-5">
                <div class="popular_event_list">
                    <h3 class="wrap_title">Schedule a Service</h3>
                    <ul class="unordered_list_block">

                        <div class="card card-calendar">
                            <div class="card-body p-3">
                                <?php if ($this->identity()) : ?>
                                    <div class="form_item m-0">
                                        <label for="input_jubject" class="input_title">Select Cohort</label>
                                        <select v-if="cohort.length" v-model="selectedCohort" name="subject" id="input_jubject">
                                            <!--  <option value="subject" selected>Choose Subject</option> -->
                                            <option v-for="coo in cohort" :value="coo.id">{{coo.cohort}} ({{coo.startDate.date}})</option>


                                        </select>
                                    </div>
                                    <div class="btn_wrap pb-0">
                                        <button :disabled="isSubmitting" @click="submitCohort()" class="btn border_dark btn-block"> <span>
                                                <small>CREATE</small>

                                            </span></button>
                                    </div>
                                <?php else : ?>
                                    <a class="btn border_dark" href="<?= $this->url("app", ["action" => "refer"]) ?>">
                                        <span>
                                            <small>LOGIN</small>

                                        </span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="deco_item shape_img_1" data-parallax='{"y" : 130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
    <div class="deco_item shape_img_2" data-parallax='{"x" : -130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
    <div class="deco_item shape_img_3" data-parallax='{"y" : -130, "smoothness": 6}'>
        <img src="assets/images/shape/shape_img_3.png" alt="Terces – Online Learning Platform">
    </div>
</section>
<!-- Popular Event Section - End
        ================================================== -->


<script>
    const appxx = Vue.createApp({
        data() {
            return {
                ll: "LLL",
                cohort: [],
                selectedCohort: "",
                isSubmitting: false,
            }
        },
        mounted() {
            this.getCohort();
        },
        methods: {
            getCohort() {
                axios.get("/get-internship-cohort").then((result) => {
                    if (result.status == 200) {
                        this.cohort = result.data.data;
                    }
                }).catch((err) => {

                });
            },

            submitCohort() {
                this.isSubmitting = true;
                if (this.selectedCohort == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Required Field",
                        text: "Please select a cohort"
                    });
                    this.isSubmitting = false;
                } else {
                    let formData = new FormData();
                    formData.append("cohort", this.selectedCohort)
                    axios.post("/internship-payment", formData).then((result) => {
                        if (result.status == 202) {
                            window.location.href = "/internship-payment";
                            this.isSubmitting = false;
                        }
                    }).catch((err) => {
                        Swal.fire({
                            icon: "error",
                            title: "Oops",
                            text: err.response.data.message
                        });
                        this.isSubmitting = false;
                    });
                }

            }
        },
    });
    appxx.mount("#kki");
</script>