<?php

use General\Service\GeneralService;
?>
<!-- Page Section - Start
        ================================================== -->
<section class="page_banner">
    <div class="container">
        <div class="content_wrapper">
            <div class="row align-items-center">
                <div class="col col-lg-7">
                    <ul class="breadcrumb_nav unordered_list">
                        <li><a href="">Home</a></li>
                        <li><a href="">Course</a></li>
                        <li><?= GeneralService::GENERAL_TRAINING_FREE ?></li>
                    </ul>
                    <h1 class="page_title">
                        Begin Your Business Analysis Journey
                    </h1>
                    <ul class="meta_info_list unordered_list">
                        <li>
                            <i class="fas fa-chart-bar"></i>
                            <span>Beginner</span>
                        </li>
                        <li>
                            <i class="fas fa-clock"></i>
                            <span>2 Hours</span>
                        </li>
                        <!--<li>
                      <i class="fas fa-star"></i>
                      <span>3.5 (3k reviews)</span>
                    </li>-->
                    </ul>
                    <ul class="btns_group unordered_list">
                        <li>
                            <div class="item_price">
                                <del class="remove_price">$1000</del>
                                <span class="sale_price">Free</span>
                            </div>
                        </li>
                        <li>
                            <a href="<?php if($this->identity()){ 
                                echo $this->url('application', ["action" => "business-analysis-masterclass-register"]);
                            }else{ echo $this->url("register") ;} ?>" class="btn btn_dark">
                                <span>
                                    <small>Register Now</small>
                                    <small>Register Now</small>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col col-lg-5">
                    <div class="image_widget page_banner_image">
                        <img src="assets/images/2.png" alt="Terces – Online Learning Platform">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page Section - End
        ================================================== -->

<!-- Courses Info Section - Start
        ================================================== -->
<section class="details_section courses_info_section section_space_lg">
    <div class="container">
        <div class="row">
            <div class="col col-lg-6">
                <div class="content_wrap">
                    <div class="section_heading">
                        <h2 class="heading_text mb-0">
                            What You will Learn
                        </h2>
                    </div>
                    <ul class="info_list unordered_list_block">
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Introduction to Business analysis
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                The business analyst
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analyst responsibilities in a project
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Qualifications of a business analyst
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analyst core concept model
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Business analysis knowledge areas
                            </span>
                        </li>
                        <li>
                            <i class="fas fa-check"></i>
                            <span>
                                Core skills of a business analyst
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col col-lg-3 col-md-6">
                <div class="service_item" data-magnetic>
                    <div class="item_icon">
                        <img src="assets/images/icon/icon_desktop.svg" alt="Terces – Online Learning Platform">
                    </div>
                    <div class="item_content">
                        <h3 class="item_title">Course Details</h3>
                        <ul class="info_list unordered_list_block">
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Zoom/Video Tutorials</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>20% Voucher</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Free Resources</span>
                            </li>

                            <li>
                                <i class="fas fa-square"></i>
                                <span>Self Paced</span>
                            </li>

                            <li>
                                <i class="fas fa-square"></i>
                                <span>Access to Terces Job portal</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col col-lg-3 col-md-6">
                <div class="service_item" data-magnetic>
                    <div class="item_icon">
                        <img src="assets/images/icon/icon_calendar.svg" alt="Terces – Online Learning Platform">
                    </div>
                    <div class="item_content">
                        <h3 class="item_title">Duration Course</h3>
                        <ul class="info_list unordered_list_block">
                            <li>
                                <i class="fas fa-square"></i>
                                <span>3 Hours</span>
                            </li>
                            <li>
                                <i class="fas fa-square"></i>
                                <span>Zoom/Video</span>
                            </li>
                            <!--<li>
                <i class="fas fa-square"></i>
                <span>3 Hours of Consultations</span>
              </li>
              <li>
                <i class="fas fa-square"></i>
                <span>1.5 Hours Webinar</span>
              </li> -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Course Details Section - Start
        ================================================== -->
<section id="materclass" class="details_section course_details_section">
    <div class="container">
        <div class="row">

            <div class="col col-lg-8 order-lg-last">
                <div class="ps-lg-5">
                    <div class="section_heading">
                        <h2 class="heading_text">
                            {{activeData.title}}
                        </h2>
                    </div>
                    <div class="intro_video mb-4">
                        <div class="video_wrap">
                            <img src="https://s3.amazonaws.com/aibnigeria/1692605051_oie_hYYx6lPuBea5.png" alt="Collab – Online Learning Platform">
                            <a class="video_play_btn popup_video" :href="activeData.video">
                                <span class="icon"><i class="fas fa-play"></i></span>
                            </a>
                        </div>
                    </div>

                    <a class="btn border_dark btn_small" href="#!">
                        <span>
                            <small><img src="/assets/images/icon/icon_clip.svg" alt="Collab – Online Learning Platform">
                                Resources</small>
                            <small><img src="/assets/images/icon/icon_clip_white.svg" alt="Collab – Online Learning Platform"> Resources</small>
                        </span>
                    </a>
                </div>
            </div>

            <div class="col col-lg-4">
                <div class="accordion style_2" id="corse_details_accordion">
                    <div class="accordion-item">
                        <div class="accordion-button" role="button" data-bs-toggle="collapse" data-bs-target="#collapse_one" aria-expanded="true">
                            Section 1. Business analysis foundation
                        </div>
                        <div id="collapse_one" class="accordion-collapse collapse show" data-bs-parent="#corse_details_accordion">
                            <div v-for="(sec, index) in section1" class="accordion-body">

                                <div v-if="index <= 7" class="checkbox_item">

                                    <label for="checkbox_1_1">
                                        <?php if ($this->identity()) : ?>
                                            <a @click="isClickContent(index)">
                                                {{sec.title}}</a>
                                        <?php else : ?>
                                            <a href="<?= $this->url("application", ["action" => "register"]) ?>">
                                                {{sec.title}}</a>
                                        <?php endif; ?>
                                    </label>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- Course Details Section - End
        ================================================== -->


<?= $this->partial("partials_coming_free_training") ?>
<?= $this->partial("partials_courselist") ?>


<?php $this->partial("partials_newsletter")  ?>

<script>
    const materclass = Vue.createApp({
        data() {
            return {
                section1: "",
                activeData: {

                    "title": "Introduction to Business Analysis",
                    "video": "https://www.youtube.com/watch?v=6DOVPrTdTiY"
                },
            }
        },
        mounted() {
            this.getSectionOne();
        },
        methods: {
            isClickContent(inn) {
                this.activeData = this.section1[inn];
            },
            getSectionOne() {

                axios.get("/get-section-one").then((result) => {

                    if (result.status == 200) {
                        this.section1 = result.data.data;
                    }
                }).catch((err) => {

                });
            }
        },
    });
    materclass.mount("#materclass")
</script>