  <?php

    use function PHPUnit\Framework\isNull;
    use General\Service\GeneralService;

    echo $this->headtitle("P6 Oracle Rebate");

    ?>

  <!-- Call To Action Section - Start
        ================================================== -->


  <section class="calltoaction_section section_space_lg bg_dark decoration_wrap">
      <div class="container">
          <div class="row align-items-center">
              <div class="col col-lg-6">


                  <!--    <h2 class="heading_text text-white">
                      Select Payment Methods
                  </h2> -->
                  <br>
                  <div class="section_heading mb-lg-0">
                      <h2 class="heading_text text-white">
                          <?= GeneralService::GENERAL_ORACLE_P6  ?>
                      </h2>
                      <p class="heading_description mb-0 text-white">
                          <!--  Rhoncus dolor purus non enim praesent elementum facilisis. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Iaculis eu non diam phasellus vestibulum lorem sed risus. -->
                          This payment is only valid for the specific duration
                     <!-- <ol class="text-white">
                          <li> Business Analysis and Software Development Lifecycle</li>
                          <li> Requirements gathering and solution definition</li>
                          <li>Software Testing and Wire-framing</li>
                          <li>Change management and UML Toolkit</li>
                          <li>Agile and Waterfall methodologies</li>
                          <li>Project Management activities</li>
                          <li>Creating essential Business Analysis artifacts</li>
                          <li>Vendor Management</li>
                          <li>Tackling large enterprise-wide projects that set you apart in interviews</li>
                      </ol>
                      </p>
                      <p class="heading_description mb-0 text-white">

                          This is your opportunity to immerse yourself in a world of learning:<br>
                      <ol class="text-white">
                          <li>Dive into a wealth of study materials for one month</li>
                          <li>Engage in a two-month hands-on internship with esteemed organizations</li>
                          <li>Gain practical exposure to business analysis, data management, and more</li>
                          <li>Receive valuable mentorship and guidance from industry experts</li>
                          <li>Achieve a Certificate of Completion, a powerful addition to your resume</li>
                          <li>Get Canadian experience that would easily get you a Canadian job</li>
                          <li>Get job refferals</li>
                          <li>Get interview help </li>
                      </ol>
                      </p>
                      <p class="heading_description mb-0 text-white">
                          Your path to a successful career starts here! Ready to fast-track your journey? Enroll today and step into a brighter future!
                          Stay updated by following us across all social media channels—just a click away!"
                      </p> -->

                  </div>
              </div>
              <div id="rebate" class="col col-lg-6">
                  <div class="col col-lg-12">
                      <div class="pricing_card text-center tilt">
                          <h3 class="card_heading">Amount Payable</h3>
                          <div class="pricing_wrap">


                              <span class="price_value"><sup><?php  //$this->currencyFormat($data->getCost(), "USD") 
                                                                ?></span>


                          </div>
                          <hr>

                          <div class="btn_wrap pb-0">
                              <?php if ($this->identity()) : ?>

                                  <!-- <div id="paypal-button-container"></div> 

                                  <button class="btn border_dark" @click=" payWithPaystack()">
                                      <span>
                                          <small>Pay Now</small>
                                     <small>Pay Now</small>
                                      </span>
                                  </button> -->

                                  <h4>Enter Prefered Amount</h4>
                                  <div class="form_item">
                                      <div v-if="isErrorAmountPayable" style="font-size: small; color:red">{{errorAmountPayable}}</div>
                                      <input v-model="amountPayable" type="text" placeholder="Amount Payable" @input="evaluatePayableBound()">
                                  </div>
                                  <!--   <h3 class="widget_title">Get More Benefits with Our Plans</h3> -->
                                  <a class="btn border_dark w-100" @click="generateBuyNowUrl()">
                                      <span>
                                          <small>Pay Now(USD)</small>
                                          <small>Click (USD)</small>
                                      </span>
                                  </a>
                                  <!--
                                  <button class="btn btn_dark w-100" @click="toggleinterac()">
                                      <span>
                                          <small>Pay with Interac (USD)</small>
                                          <small>Pay with Interac (USD)</small>
                                      </span>
                                  </button>
                                  <a class="btn border_dark w-100" href="<?= $this->url("application", ["action" => "buy-course-naira", "id" => ""])  //$data->getUuid()
                                                                            ?>">
                                      <span>
                                          <small>Pay in Naira</small>
                                          <small>Pay in Naira</small>
                                      </span>
                                  </a> -->

                              <?php else : ?>
                                  <a class="btn border_dark" href="<?= $this->url("app", ["action" => "refer"]) ?>">
                                      <span>
                                          <small>Pay Now</small>

                                      </span>
                                  </a>
                              <?php endif; ?>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>





  </section>
  <!-- Call To Action Section - End
        ================================================== -->
  <script src="https://js.paystack.co/v2/inline.js"></script>

  <script>
      const p6rebate = Vue.createApp({
          data() {
              return {
                  activePayment: [],
                  amountPayable: 150,
                  minAmountPayable: 150,
                  maxAmountPayable: 695.95,

                  errorAmountPayable: "",
                  isErrorAmountPayable: false,


              }
          },

          mounted() {
              this.evaluatePayableBound();
          },

          methods: {
              evaluatePayableBound() {
                  if (this.amountPayable < this.minAmountPayable) {
                      this.errorAmountPayable = `We require a minimum payment $${this.minAmountPayable}`;
                      this.isErrorAmountPayable = true;
                  } else if (this.amountPayable > this.maxAmountPayable) {
                      this.errorAmountPayable = `We would love to take more than $${this.minAmountPayable}, but no thanks`;
                      this.isErrorAmountPayable = true;
                  } else {
                      //   this.
                      this.isErrorAmountPayable = false
                  }
              },



              generateBuyNowUrl() {
                  if (this.isErrorAmountPayable) {
                      Swal.fire({
                          icon: "error",
                          title: "Amount Error",
                          text: this.errorAmountPayable
                      });
                  } else {
                      window.location.href = `/buy-p6-rebate-course?pp=${this.amountPayable}`
                  }

              },

              toggleinterac() {

              }
          },
      });
      p6rebate.mount("#rebate");
  </script>