<?php echo $this->headtitle("Schedule"); ?>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.2.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.2.0/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.2.0/main.js"></script>
<link href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.2.0/main.min.css" rel="stylesheet" />
<div class="col-12 ms-auto">
    <div class="d-flex mb-4">
        <div class="pe-4 mt-1 position-relative ms-auto">
            <p class="text-secondary text-xs font-weight-bold mb-2">Team members:</p>
            <div class="d-flex align-items-center justify-content-center">
                <div class="avatar-group">
                    <a href="javascript:;" class="avatar avatar-sm rounded-circle" data-bs-toggle="tooltip" title="Jessica Rowland">
                        <img alt="Image placeholder" src="../../assets/img/team-1.jpg" class="">
                    </a>
                    <a href="javascript:;" class="avatar avatar-sm rounded-circle" data-bs-toggle="tooltip" title="Audrey Love">
                        <img alt="Image placeholder" src="../../assets/img/team-2.jpg" class="rounded-circle">
                    </a>
                    <a href="javascript:;" class="avatar avatar-sm rounded-circle" data-bs-toggle="tooltip" title="Michael Lewis">
                        <img alt="Image placeholder" src="../../assets/img/team-3.jpg" class="rounded-circle">
                    </a>
                    <a href="javascript:;" class="avatar avatar-sm rounded-circle" data-bs-toggle="tooltip" title="Lucia Linda">
                        <img alt="Image placeholder" src="../../assets/img/team-4.jpg" class="rounded-circle">
                    </a>
                    <a href="javascript:;" class="avatar avatar-sm rounded-circle" data-bs-toggle="tooltip" title="Ronald Miller">
                        <img alt="Image placeholder" src="../../assets/img/team-5.jpg" class="rounded-circle">
                    </a>
                </div>
            </div>
            <hr class="vertical dark mt-0">
        </div>
        <div class="ps-4">
            <button class="btn btn-outline-dark btn-icon-only mb-0 mt-3" data-bs-toggle="modal" data-target="#new-board-modal">
                <i class="fa fa-plus"></i>
            </button>
        </div>
    </div>
</div>
<div class="col-xl-9">
    <div class="card card-calendar">
        <div class="card-body p-3">
            <div class="calendar" data-bs-toggle="calendar" id="calendar"></div>
        </div>
    </div>
</div>

<script src="/assets/js/fullcalendar.min.js"></script>
<script>
    var eventsArray = [];
    var calendar = new FullCalendar.Calendar(document.getElementById("calendar"), {
        // contentHeight: 'auto',
        // // initialView: "dayGridMonth",
        // // initialView: 'timeGridFourDay',
        // // headerToolbar: {
        // //     start: 'title', // will normally be on the left. if RTL, will be on the right
        // //     center: '',
        // //     end: 'today prev,next' // will normally be on the right. if RTL, will be on the left
        // // },
        // header: {
        //     left: "prev,next today",
        //     center: "title",
        //     right: "month,agendaWeek,agendaDay,listWeek"
        // },
        // defaultView: "agendaWeek",
        // minTime: "07:00:00",
        // maxTime: "20:15:00",
        // displayEventEnd: true,

        // hiddenDays: [1, 2, 3, 6, 7],
        // weekends: false,
        // dateClick: function(info) {
        //     alert('Clicked on: ' + info.dateStr);

        //     eventsArray.push({
        //         date: info.dateStr,
        //         title: "test event added from click"
        //     });

        //     calendar.refetchEvents();
        // },

        // eventClick: function(info) {
        //     alert(info.event.title)
        // },



        // // initialDate: 'today',
        // // events: [{
        // //         title: 'Call with Dave',
        // //         start: '2020-11-18',
        // //         end: '2020-11-18',
        // //         className: 'bg-gradient-danger'
        // //     },

        // //     {
        // //         title: 'Lunch meeting',
        // //         start: '2020-11-21',
        // //         end: '2020-11-22',
        // //         className: 'bg-gradient-warning'
        // //     },

        // //     {
        // //         title: 'All day conference',
        // //         start: '2020-11-29',
        // //         end: '2020-11-29',
        // //         className: 'bg-gradient-success'
        // //     },

        // //     {
        // //         title: 'Meeting with Mary',
        // //         start: '2020-12-01',
        // //         end: '2020-12-01',
        // //         className: 'bg-gradient-info'
        // //     },

        // //     {
        // //         title: 'Winter Hackaton',
        // //         start: '2020-12-03',
        // //         end: '2020-12-03',
        // //         className: 'bg-gradient-danger'
        // //     },

        // //     {
        // //         title: 'Digital event',
        // //         start: '2020-12-07',
        // //         end: '2020-12-09',
        // //         className: 'bg-gradient-warning'
        // //     },

        // //     {
        // //         title: 'Marketing event',
        // //         start: '2020-12-10',
        // //         end: '2020-12-10',
        // //         className: 'bg-gradient-primary'
        // //     },

        // //     {
        // //         title: 'Dinner with Family',
        // //         start: '2020-12-19',
        // //         end: '2020-12-19',
        // //         className: 'bg-gradient-danger'
        // //     },

        // //     {
        // //         title: 'Black Friday',
        // //         start: '2020-12-23',
        // //         end: '2020-12-23',
        // //         className: 'bg-gradient-info'
        // //     },

        // //     {
        // //         title: 'Cyber Week',
        // //         start: '2020-12-02',
        // //         end: '2020-12-02',
        // //         className: 'bg-gradient-warning'
        // //     },

        // // ],

        // events: function(info, successCallback, failureCallback) {
        //     successCallback(eventsArray);
        // },
        // resourceLabelText: 'Rooms',
        // resources: 'https://fullcalendar.io/demo-resources.json',
        // views: {
        //     // timelineHours: {
        //     //     type: 'timeline',
        //     //     duration: {
        //     //         // hours: 8
        //     //     },
        //     //     buttonText: 'hours'
        //     // },
        //     // timeGridFourDay: {
        //     //     type: 'timeGrid',
        //     //     allday: false,
        //     //     duration: {
        //     //         days: 1
        //     //     }
        //     // },
        //     month: {
        //         titleFormat: {
        //             month: "long",
        //             year: "numeric"
        //         }
        //     },
        //     agendaWeek: {
        //         titleFormat: {
        //             month: "long",
        //             year: "numeric",
        //             day: "numeric"
        //         }
        //     },
        //     agendaDay: {
        //         titleFormat: {
        //             month: "short",
        //             year: "numeric",
        //             day: "numeric"
        //         }
        //     }
        // },

        header: {
            left: "prev,next today",
            center: "title",
            right: "month,agendaWeek,agendaDay,listWeek"
        },
        view:{
             timelineHours: {
                type: 'timeline',
                duration: {
                    // hours: 8
                },
                buttonText: 'hours'
            },
        },
        defaultView: "agendaDay",
        minTime: "07:00:00",
        maxTime: "20:15:00",
        displayEventEnd: true,

    });



    calendar.render();







    // document.addEventListener('DOMContentLoaded', function() {
    //     var calendarEl = document.getElementById('calendar');

    //     var calendar = new FullCalendar.Calendar(calendarEl, {
    //         height: 600,
    //         plugins: ['dayGrid', 'interaction'],

    //         dateClick: function(info) {
    //             alert('Clicked on: ' + info.dateStr);

    //             eventsArray.push({
    //                 date: info.dateStr,
    //                 title: "test event added from click"
    //             });

    //             calendar.refetchEvents();
    //         },

    //         eventClick: function(info) {
    //             alert(info.event.title)
    //         },

    //         events: function(info, successCallback, failureCallback) {
    //             successCallback(eventsArray);
    //         }
    //     });

    //     calendar.render();
    // });





    var ctx1 = document.getElementById("chart-line-1").getContext("2d");

    var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);

    gradientStroke1.addColorStop(1, 'rgba(255,255,255,0.3)');
    gradientStroke1.addColorStop(0.2, 'rgba(72,72,176,0.0)');
    gradientStroke1.addColorStop(0, 'rgba(203,12,159,0)'); //purple colors
</script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>